/* tslint:disable */
/* eslint-disable */
/**
 * Avalara 1099 & W-9 API Definition
 * ## 🔐 Authentication  Use **username/password** or generate a **license key** from: *Avalara Portal → Settings → License and API Keys*.  [More on authentication methods](https://developer.avalara.com/avatax-dm-combined-erp/common-setup/authentication/authentication-methods/)  [Test your credentials](https://developer.avalara.com/avatax/test-credentials/)  ## 📘 API & SDK Documentation  [Avalara SDK (.NET) on GitHub](https://github.com/avadev/Avalara-SDK-DotNet#avalarasdk--the-unified-c-library-for-next-gen-avalara-services)  [Code Examples – 1099 API](https://github.com/avadev/Avalara-SDK-DotNet/blob/main/docs/A1099/V2/Class1099IssuersApi.md#call1099issuersget)
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@avalara.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../../../runtime';
/**
 * 
 * @export
 * @interface CompanyResponseModel
 */
export interface CompanyResponseModel {
    /**
     * 
     * @type {string}
     * @memberof CompanyResponseModel
     */
    id?: string;
    /**
     * 
     * @type {Date}
     * @memberof CompanyResponseModel
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof CompanyResponseModel
     */
    updatedAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof CompanyResponseModel
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof CompanyResponseModel
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof CompanyResponseModel
     */
    address?: string;
    /**
     * 
     * @type {string}
     * @memberof CompanyResponseModel
     */
    city?: string;
    /**
     * 
     * @type {string}
     * @memberof CompanyResponseModel
     */
    state?: string;
    /**
     * 
     * @type {string}
     * @memberof CompanyResponseModel
     */
    zip?: string;
    /**
     * 
     * @type {string}
     * @memberof CompanyResponseModel
     */
    telephone?: string;
    /**
     * 
     * @type {string}
     * @memberof CompanyResponseModel
     */
    tin?: string;
    /**
     * 
     * @type {string}
     * @memberof CompanyResponseModel
     */
    dbaName?: string;
    /**
     * 
     * @type {string}
     * @memberof CompanyResponseModel
     */
    referenceId?: string;
    /**
     * 
     * @type {boolean}
     * @memberof CompanyResponseModel
     */
    doTinMatch?: boolean;
    /**
     * 
     * @type {string}
     * @memberof CompanyResponseModel
     */
    groupName?: string;
    /**
     * 
     * @type {string}
     * @memberof CompanyResponseModel
     */
    foreignProvince?: string;
    /**
     * 
     * @type {string}
     * @memberof CompanyResponseModel
     */
    countryCode?: string;
    /**
     * 
     * @type {boolean}
     * @memberof CompanyResponseModel
     */
    resendRequests?: boolean;
    /**
     * 
     * @type {number}
     * @memberof CompanyResponseModel
     */
    resendIntervalDays?: number | null;
    /**
     * 
     * @type {number}
     * @memberof CompanyResponseModel
     */
    maxReminderAttempts?: number | null;
}



/**
 * Check if a given object implements the CompanyResponseModel interface.
 */
export function instanceOfCompanyResponseModel(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CompanyResponseModelFromJSON(json: any): CompanyResponseModel {
    return CompanyResponseModelFromJSONTyped(json, false);
}

export function CompanyResponseModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): CompanyResponseModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'createdAt': !exists(json, 'createdAt') ? undefined : (new Date(json['createdAt'])),
        'updatedAt': !exists(json, 'updatedAt') ? undefined : (new Date(json['updatedAt'])),
        'name': !exists(json, 'name') ? undefined : json['name'],
        'email': !exists(json, 'email') ? undefined : json['email'],
        'address': !exists(json, 'address') ? undefined : json['address'],
        'city': !exists(json, 'city') ? undefined : json['city'],
        'state': !exists(json, 'state') ? undefined : json['state'],
        'zip': !exists(json, 'zip') ? undefined : json['zip'],
        'telephone': !exists(json, 'telephone') ? undefined : json['telephone'],
        'tin': !exists(json, 'tin') ? undefined : json['tin'],
        'dbaName': !exists(json, 'dbaName') ? undefined : json['dbaName'],
        'referenceId': !exists(json, 'referenceId') ? undefined : json['referenceId'],
        'doTinMatch': !exists(json, 'doTinMatch') ? undefined : json['doTinMatch'],
        'groupName': !exists(json, 'groupName') ? undefined : json['groupName'],
        'foreignProvince': !exists(json, 'foreignProvince') ? undefined : json['foreignProvince'],
        'countryCode': !exists(json, 'countryCode') ? undefined : json['countryCode'],
        'resendRequests': !exists(json, 'resendRequests') ? undefined : json['resendRequests'],
        'resendIntervalDays': !exists(json, 'resendIntervalDays') ? undefined : json['resendIntervalDays'],
        'maxReminderAttempts': !exists(json, 'maxReminderAttempts') ? undefined : json['maxReminderAttempts'],
    };
}

export function CompanyResponseModelToJSON(value?: CompanyResponseModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'createdAt': value.createdAt === undefined ? undefined : (value.createdAt.toISOString()),
        'updatedAt': value.updatedAt === undefined ? undefined : (value.updatedAt.toISOString()),
        'name': value.name,
        'email': value.email,
        'address': value.address,
        'city': value.city,
        'state': value.state,
        'zip': value.zip,
        'telephone': value.telephone,
        'tin': value.tin,
        'dbaName': value.dbaName,
        'referenceId': value.referenceId,
        'doTinMatch': value.doTinMatch,
        'groupName': value.groupName,
        'foreignProvince': value.foreignProvince,
        'countryCode': value.countryCode,
        'resendRequests': value.resendRequests,
        'resendIntervalDays': value.resendIntervalDays,
        'maxReminderAttempts': value.maxReminderAttempts,
    };
}
