/* tslint:disable */
/* eslint-disable */
/**
 * Avalara 1099 & W-9 API Definition
 * ## 🔐 Authentication  Generate a **license key** from: *[Avalara Portal](https://www.avalara.com/us/en/signin.html) → Settings → License and API Keys*.  [More on authentication methods](https://developer.avalara.com/avatax-dm-combined-erp/common-setup/authentication/authentication-methods/)  [Test your credentials](https://developer.avalara.com/avatax/test-credentials/)  ## 📘 API & SDK Documentation  [Avalara SDK (.NET) on GitHub](https://github.com/avadev/Avalara-SDK-DotNet#avalarasdk--the-unified-c-library-for-next-gen-avalara-services)  [Code Examples – 1099 API](https://github.com/avadev/Avalara-SDK-DotNet/blob/main/docs/A1099/V2/Class1099IssuersApi.md#call1099issuersget)
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@avalara.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { W4FormResponse } from './W4FormResponse';
import {
    instanceOfW4FormResponse,
    W4FormResponseFromJSON,
    W4FormResponseFromJSONTyped,
    W4FormResponseToJSON,
} from './W4FormResponse';
import type { W8BenEFormResponse } from './W8BenEFormResponse';
import {
    instanceOfW8BenEFormResponse,
    W8BenEFormResponseFromJSON,
    W8BenEFormResponseFromJSONTyped,
    W8BenEFormResponseToJSON,
} from './W8BenEFormResponse';
import type { W8BenFormResponse } from './W8BenFormResponse';
import {
    instanceOfW8BenFormResponse,
    W8BenFormResponseFromJSON,
    W8BenFormResponseFromJSONTyped,
    W8BenFormResponseToJSON,
} from './W8BenFormResponse';
import type { W8ImyFormResponse } from './W8ImyFormResponse';
import {
    instanceOfW8ImyFormResponse,
    W8ImyFormResponseFromJSON,
    W8ImyFormResponseFromJSONTyped,
    W8ImyFormResponseToJSON,
} from './W8ImyFormResponse';
import type { W9FormResponse } from './W9FormResponse';
import {
    instanceOfW9FormResponse,
    W9FormResponseFromJSON,
    W9FormResponseFromJSONTyped,
    W9FormResponseToJSON,
} from './W9FormResponse';

/**
 * @type CreateW9Form201Response
 * 
 * @export
 */
export type CreateW9Form201Response = W4FormResponse | W8BenEFormResponse | W8BenFormResponse | W8ImyFormResponse | W9FormResponse;

export function CreateW9Form201ResponseFromJSON(json: any): CreateW9Form201Response {
    return CreateW9Form201ResponseFromJSONTyped(json, false);
}

export function CreateW9Form201ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateW9Form201Response {
    if (json == null) {
        return json;
    }
    if (instanceOfW4FormResponse(json)) {
        return W4FormResponseFromJSONTyped(json, true);
    }
    if (instanceOfW8BenEFormResponse(json)) {
        return W8BenEFormResponseFromJSONTyped(json, true);
    }
    if (instanceOfW8BenFormResponse(json)) {
        return W8BenFormResponseFromJSONTyped(json, true);
    }
    if (instanceOfW8ImyFormResponse(json)) {
        return W8ImyFormResponseFromJSONTyped(json, true);
    }
    if (instanceOfW9FormResponse(json)) {
        return W9FormResponseFromJSONTyped(json, true);
    }
}

export function CreateW9Form201ResponseToJSON(value?: CreateW9Form201Response | null): any {
    if (value == null) {
        return value;
    }

    if (instanceOfW4FormResponse(value)) {
        return W4FormResponseToJSON(value as W4FormResponse);
    }
    if (instanceOfW8BenEFormResponse(value)) {
        return W8BenEFormResponseToJSON(value as W8BenEFormResponse);
    }
    if (instanceOfW8BenFormResponse(value)) {
        return W8BenFormResponseToJSON(value as W8BenFormResponse);
    }
    if (instanceOfW8ImyFormResponse(value)) {
        return W8ImyFormResponseToJSON(value as W8ImyFormResponse);
    }
    if (instanceOfW9FormResponse(value)) {
        return W9FormResponseToJSON(value as W9FormResponse);
    }

    return {};
}

