/* tslint:disable */
/* eslint-disable */
/**
 * Avalara 1099 & W-9 API Definition
 * ## 🔐 Authentication  Generate a **license key** from: *[Avalara Portal](https://www.avalara.com/us/en/signin.html) → Settings → License and API Keys*.  [More on authentication methods](https://developer.avalara.com/avatax-dm-combined-erp/common-setup/authentication/authentication-methods/)  [Test your credentials](https://developer.avalara.com/avatax/test-credentials/)  ## 📘 API & SDK Documentation  [Avalara SDK (.NET) on GitHub](https://github.com/avadev/Avalara-SDK-DotNet#avalarasdk--the-unified-c-library-for-next-gen-avalara-services)  [Code Examples – 1099 API](https://github.com/avadev/Avalara-SDK-DotNet/blob/main/docs/A1099/V2/Class1099IssuersApi.md#call1099issuersget)
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@avalara.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { IssuerCommand } from './IssuerCommand';
import {
    instanceOfIssuerCommand,
    IssuerCommandFromJSON,
    IssuerCommandFromJSONTyped,
    IssuerCommandToJSON,
} from './IssuerCommand';
import type { IssuerResponse } from './IssuerResponse';
import {
    instanceOfIssuerResponse,
    IssuerResponseFromJSON,
    IssuerResponseFromJSONTyped,
    IssuerResponseToJSON,
} from './IssuerResponse';

/**
 * @type CreateIssuerRequest
 * 
 * @export
 */
export type CreateIssuerRequest = IssuerCommand | IssuerResponse;

export function CreateIssuerRequestFromJSON(json: any): CreateIssuerRequest {
    return CreateIssuerRequestFromJSONTyped(json, false);
}

export function CreateIssuerRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateIssuerRequest {
    if (json == null) {
        return json;
    }
    if (instanceOfIssuerCommand(json)) {
        return IssuerCommandFromJSONTyped(json, true);
    }
    if (instanceOfIssuerResponse(json)) {
        return IssuerResponseFromJSONTyped(json, true);
    }
}

export function CreateIssuerRequestToJSON(value?: CreateIssuerRequest | null): any {
    if (value == null) {
        return value;
    }

    if (instanceOfIssuerCommand(value)) {
        return IssuerCommandToJSON(value as IssuerCommand);
    }
    if (instanceOfIssuerResponse(value)) {
        return IssuerResponseToJSON(value as IssuerResponse);
    }

    return {};
}

