/* tslint:disable */
/* eslint-disable */
/**
 * Avalara 1099 & W-9 API Definition
 * ## 🔐 Authentication  Use **username/password** or generate a **license key** from: *Avalara Portal → Settings → License and API Keys*.  [More on authentication methods](https://developer.avalara.com/avatax-dm-combined-erp/common-setup/authentication/authentication-methods/)  [Test your credentials](https://developer.avalara.com/avatax/test-credentials/)  ## 📘 API & SDK Documentation  [Avalara SDK (.NET) on GitHub](https://github.com/avadev/Avalara-SDK-DotNet#avalarasdk--the-unified-c-library-for-next-gen-avalara-services)  [Code Examples – 1099 API](https://github.com/avadev/Avalara-SDK-DotNet/blob/main/docs/A1099/V2/Class1099IssuersApi.md#call1099issuersget)
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@avalara.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../../../runtime';
import {
    StateAndLocalWithholdingRequest,
    StateAndLocalWithholdingRequestFromJSON,
    StateAndLocalWithholdingRequestFromJSONTyped,
    StateAndLocalWithholdingRequestToJSON,
} from './StateAndLocalWithholdingRequest';

/**
 * 
 * @export
 * @interface Form1099NecRequest
 */
export interface Form1099NecRequest {
    /**
     * 
     * @type {StateAndLocalWithholdingRequest}
     * @memberof Form1099NecRequest
     */
    stateAndLocalWithholding?: StateAndLocalWithholdingRequest;
    /**
     * 
     * @type {boolean}
     * @memberof Form1099NecRequest
     */
    secondTinNotice?: boolean;
    /**
     * 
     * @type {number}
     * @memberof Form1099NecRequest
     */
    nonemployeeCompensation?: number;
    /**
     * 
     * @type {boolean}
     * @memberof Form1099NecRequest
     */
    payerMadeDirectSales?: boolean;
    /**
     * 
     * @type {number}
     * @memberof Form1099NecRequest
     */
    federalIncomeTaxWithheld?: number;
    /**
     * 
     * @type {string}
     * @memberof Form1099NecRequest
     */
    type?: string;
    /**
     * 
     * @type {string}
     * @memberof Form1099NecRequest
     */
    issuerId?: string;
    /**
     * 
     * @type {string}
     * @memberof Form1099NecRequest
     */
    issuerReferenceId?: string;
    /**
     * 
     * @type {string}
     * @memberof Form1099NecRequest
     */
    issuerTin?: string;
    /**
     * 
     * @type {number}
     * @memberof Form1099NecRequest
     */
    taxYear?: number;
    /**
     * 
     * @type {string}
     * @memberof Form1099NecRequest
     */
    referenceId?: string;
    /**
     * 
     * @type {string}
     * @memberof Form1099NecRequest
     */
    recipientName?: string;
    /**
     * 
     * @type {string}
     * @memberof Form1099NecRequest
     */
    recipientTin?: string;
    /**
     * 
     * @type {number}
     * @memberof Form1099NecRequest
     */
    tinType?: number;
    /**
     * 
     * @type {string}
     * @memberof Form1099NecRequest
     */
    recipientSecondName?: string;
    /**
     * 
     * @type {string}
     * @memberof Form1099NecRequest
     */
    streetAddress?: string;
    /**
     * 
     * @type {string}
     * @memberof Form1099NecRequest
     */
    streetAddressLine2?: string;
    /**
     * 
     * @type {string}
     * @memberof Form1099NecRequest
     */
    city?: string;
    /**
     * 
     * @type {string}
     * @memberof Form1099NecRequest
     */
    state?: string;
    /**
     * 
     * @type {string}
     * @memberof Form1099NecRequest
     */
    zip?: string;
    /**
     * 
     * @type {string}
     * @memberof Form1099NecRequest
     */
    recipientEmail?: string;
    /**
     * 
     * @type {string}
     * @memberof Form1099NecRequest
     */
    accountNumber?: string;
    /**
     * 
     * @type {string}
     * @memberof Form1099NecRequest
     */
    officeCode?: string;
    /**
     * 
     * @type {string}
     * @memberof Form1099NecRequest
     */
    recipientNonUsProvince?: string;
    /**
     * 
     * @type {string}
     * @memberof Form1099NecRequest
     */
    countryCode?: string;
    /**
     * 
     * @type {boolean}
     * @memberof Form1099NecRequest
     */
    federalEFile?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Form1099NecRequest
     */
    postalMail?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Form1099NecRequest
     */
    stateEFile?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Form1099NecRequest
     */
    tinMatch?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Form1099NecRequest
     */
    addressVerification?: boolean;
}



/**
 * Check if a given object implements the Form1099NecRequest interface.
 */
export function instanceOfForm1099NecRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function Form1099NecRequestFromJSON(json: any): Form1099NecRequest {
    return Form1099NecRequestFromJSONTyped(json, false);
}

export function Form1099NecRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): Form1099NecRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'stateAndLocalWithholding': !exists(json, 'stateAndLocalWithholding') ? undefined : StateAndLocalWithholdingRequestFromJSON(json['stateAndLocalWithholding']),
        'secondTinNotice': !exists(json, 'secondTinNotice') ? undefined : json['secondTinNotice'],
        'nonemployeeCompensation': !exists(json, 'nonemployeeCompensation') ? undefined : json['nonemployeeCompensation'],
        'payerMadeDirectSales': !exists(json, 'payerMadeDirectSales') ? undefined : json['payerMadeDirectSales'],
        'federalIncomeTaxWithheld': !exists(json, 'federalIncomeTaxWithheld') ? undefined : json['federalIncomeTaxWithheld'],
        'type': !exists(json, 'type') ? undefined : json['type'],
        'issuerId': !exists(json, 'issuerId') ? undefined : json['issuerId'],
        'issuerReferenceId': !exists(json, 'issuerReferenceId') ? undefined : json['issuerReferenceId'],
        'issuerTin': !exists(json, 'issuerTin') ? undefined : json['issuerTin'],
        'taxYear': !exists(json, 'taxYear') ? undefined : json['taxYear'],
        'referenceId': !exists(json, 'referenceId') ? undefined : json['referenceId'],
        'recipientName': !exists(json, 'recipientName') ? undefined : json['recipientName'],
        'recipientTin': !exists(json, 'recipientTin') ? undefined : json['recipientTin'],
        'tinType': !exists(json, 'tinType') ? undefined : json['tinType'],
        'recipientSecondName': !exists(json, 'recipientSecondName') ? undefined : json['recipientSecondName'],
        'streetAddress': !exists(json, 'streetAddress') ? undefined : json['streetAddress'],
        'streetAddressLine2': !exists(json, 'streetAddressLine2') ? undefined : json['streetAddressLine2'],
        'city': !exists(json, 'city') ? undefined : json['city'],
        'state': !exists(json, 'state') ? undefined : json['state'],
        'zip': !exists(json, 'zip') ? undefined : json['zip'],
        'recipientEmail': !exists(json, 'recipientEmail') ? undefined : json['recipientEmail'],
        'accountNumber': !exists(json, 'accountNumber') ? undefined : json['accountNumber'],
        'officeCode': !exists(json, 'officeCode') ? undefined : json['officeCode'],
        'recipientNonUsProvince': !exists(json, 'recipientNonUsProvince') ? undefined : json['recipientNonUsProvince'],
        'countryCode': !exists(json, 'countryCode') ? undefined : json['countryCode'],
        'federalEFile': !exists(json, 'federalEFile') ? undefined : json['federalEFile'],
        'postalMail': !exists(json, 'postalMail') ? undefined : json['postalMail'],
        'stateEFile': !exists(json, 'stateEFile') ? undefined : json['stateEFile'],
        'tinMatch': !exists(json, 'tinMatch') ? undefined : json['tinMatch'],
        'addressVerification': !exists(json, 'addressVerification') ? undefined : json['addressVerification'],
    };
}

export function Form1099NecRequestToJSON(value?: Form1099NecRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'stateAndLocalWithholding': StateAndLocalWithholdingRequestToJSON(value.stateAndLocalWithholding),
        'secondTinNotice': value.secondTinNotice,
        'nonemployeeCompensation': value.nonemployeeCompensation,
        'payerMadeDirectSales': value.payerMadeDirectSales,
        'federalIncomeTaxWithheld': value.federalIncomeTaxWithheld,
        'type': value.type,
        'issuerId': value.issuerId,
        'issuerReferenceId': value.issuerReferenceId,
        'issuerTin': value.issuerTin,
        'taxYear': value.taxYear,
        'referenceId': value.referenceId,
        'recipientName': value.recipientName,
        'recipientTin': value.recipientTin,
        'tinType': value.tinType,
        'recipientSecondName': value.recipientSecondName,
        'streetAddress': value.streetAddress,
        'streetAddressLine2': value.streetAddressLine2,
        'city': value.city,
        'state': value.state,
        'zip': value.zip,
        'recipientEmail': value.recipientEmail,
        'accountNumber': value.accountNumber,
        'officeCode': value.officeCode,
        'recipientNonUsProvince': value.recipientNonUsProvince,
        'countryCode': value.countryCode,
        'federalEFile': value.federalEFile,
        'postalMail': value.postalMail,
        'stateEFile': value.stateEFile,
        'tinMatch': value.tinMatch,
        'addressVerification': value.addressVerification,
    };
}
