/* tslint:disable */
/* eslint-disable */
/**
 * Avalara 1099 & W-9 API Definition
 * ## 🔐 Authentication  Generate a **license key** from: *[Avalara Portal](https://www.avalara.com/us/en/signin.html) → Settings → License and API Keys*.  [More on authentication methods](https://developer.avalara.com/avatax-dm-combined-erp/common-setup/authentication/authentication-methods/)  [Test your credentials](https://developer.avalara.com/avatax/test-credentials/)  ## 📘 API & SDK Documentation  [Avalara SDK (.NET) on GitHub](https://github.com/avadev/Avalara-SDK-DotNet#avalarasdk--the-unified-c-library-for-next-gen-avalara-services)  [Code Examples – 1099 API](https://github.com/avadev/Avalara-SDK-DotNet/blob/main/docs/A1099/V2/Class1099IssuersApi.md#call1099issuersget)
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@avalara.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../../../runtime';
import {
    StateAndLocalWithholdingRequest,
    StateAndLocalWithholdingRequestFromJSON,
    StateAndLocalWithholdingRequestFromJSONTyped,
    StateAndLocalWithholdingRequestToJSON,
} from './StateAndLocalWithholdingRequest';

/**
 * 
 * @export
 * @interface FormSingleRequestBase
 */
export interface FormSingleRequestBase {
    /**
     * 
     * @type {string}
     * @memberof FormSingleRequestBase
     */
    type?: FormSingleRequestBaseTypeEnum;
    /**
     * Issuer ID
     * @type {string}
     * @memberof FormSingleRequestBase
     */
    issuerId?: string | null;
    /**
     * Reference ID
     * @type {string}
     * @memberof FormSingleRequestBase
     */
    referenceId?: string | null;
    /**
     * Recipient Tax ID Number
     * @type {string}
     * @memberof FormSingleRequestBase
     */
    recipientTin?: string;
    /**
     * Recipient name
     * @type {string}
     * @memberof FormSingleRequestBase
     */
    recipientName?: string | null;
    /**
     * Type of TIN (Tax ID Number). Will be one of:
     * * SSN
     * * EIN
     * * ITIN
     * * ATIN
     * @type {string}
     * @memberof FormSingleRequestBase
     */
    tinType?: FormSingleRequestBaseTinTypeEnum;
    /**
     * Recipient second name
     * @type {string}
     * @memberof FormSingleRequestBase
     */
    recipientSecondName?: string | null;
    /**
     * Address
     * @type {string}
     * @memberof FormSingleRequestBase
     */
    address: string;
    /**
     * Address line 2
     * @type {string}
     * @memberof FormSingleRequestBase
     */
    address2?: string | null;
    /**
     * City
     * @type {string}
     * @memberof FormSingleRequestBase
     */
    city: string;
    /**
     * US state. Required if CountryCode is "US".
     * @type {string}
     * @memberof FormSingleRequestBase
     */
    state?: string;
    /**
     * Zip/postal code
     * @type {string}
     * @memberof FormSingleRequestBase
     */
    zip?: string;
    /**
     * Recipient email address
     * @type {string}
     * @memberof FormSingleRequestBase
     */
    email?: string | null;
    /**
     * Account number
     * @type {string}
     * @memberof FormSingleRequestBase
     */
    accountNumber?: string | null;
    /**
     * Office code
     * @type {string}
     * @memberof FormSingleRequestBase
     */
    officeCode?: string | null;
    /**
     * Foreign province
     * @type {string}
     * @memberof FormSingleRequestBase
     */
    nonUsProvince?: string | null;
    /**
     * Country code, as defined at https://www.irs.gov/e-file-providers/country-codes
     * @type {string}
     * @memberof FormSingleRequestBase
     */
    countryCode: string;
    /**
     * Boolean indicating that federal e-filing should be scheduled for this form
     * @type {boolean}
     * @memberof FormSingleRequestBase
     */
    federalEFile?: boolean;
    /**
     * Boolean indicating that postal mailing to the recipient should be scheduled for this form
     * @type {boolean}
     * @memberof FormSingleRequestBase
     */
    postalMail?: boolean;
    /**
     * Boolean indicating that state e-filing should be scheduled for this form
     * @type {boolean}
     * @memberof FormSingleRequestBase
     */
    stateEFile?: boolean;
    /**
     * Boolean indicating that TIN Matching should be scheduled for this form
     * @type {boolean}
     * @memberof FormSingleRequestBase
     */
    tinMatch?: boolean;
    /**
     * Indicates whether the recipient has no TIN
     * @type {boolean}
     * @memberof FormSingleRequestBase
     */
    noTin?: boolean;
    /**
     * Second TIN notice in three years
     * @type {boolean}
     * @memberof FormSingleRequestBase
     */
    secondTinNotice?: boolean | null;
    /**
     * Boolean indicating that address verification should be scheduled for this form
     * @type {boolean}
     * @memberof FormSingleRequestBase
     */
    addressVerification?: boolean;
    /**
     * State and local withholding information
     * @type {StateAndLocalWithholdingRequest}
     * @memberof FormSingleRequestBase
     */
    stateAndLocalWithholding?: StateAndLocalWithholdingRequest | null;
}

/**
* @export
* @enum {string}
*/
export enum FormSingleRequestBaseTypeEnum {
    _1099Nec = '1099-NEC',
    _1099Misc = '1099-MISC',
    _1099Div = '1099-DIV',
    _1099R = '1099-R',
    _1099K = '1099-K',
    _1095B = '1095-B',
    _1042S = '1042-S',
    _1095C = '1095-C'
}/**
* @export
* @enum {string}
*/
export enum FormSingleRequestBaseTinTypeEnum {
    Ein = 'EIN',
    Ssn = 'SSN',
    Itin = 'ITIN',
    Atin = 'ATIN'
}

/**
 * Check if a given object implements the FormSingleRequestBase interface.
 */
export function instanceOfFormSingleRequestBase(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "address" in value;
    isInstance = isInstance && "city" in value;
    isInstance = isInstance && "countryCode" in value;

    return isInstance;
}

export function FormSingleRequestBaseFromJSON(json: any): FormSingleRequestBase {
    return FormSingleRequestBaseFromJSONTyped(json, false);
}

export function FormSingleRequestBaseFromJSONTyped(json: any, ignoreDiscriminator: boolean): FormSingleRequestBase {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': !exists(json, 'type') ? undefined : json['type'],
        'issuerId': !exists(json, 'issuerId') ? undefined : json['issuerId'],
        'referenceId': !exists(json, 'referenceId') ? undefined : json['referenceId'],
        'recipientTin': !exists(json, 'recipientTin') ? undefined : json['recipientTin'],
        'recipientName': !exists(json, 'recipientName') ? undefined : json['recipientName'],
        'tinType': !exists(json, 'tinType') ? undefined : json['tinType'],
        'recipientSecondName': !exists(json, 'recipientSecondName') ? undefined : json['recipientSecondName'],
        'address': json['address'],
        'address2': !exists(json, 'address2') ? undefined : json['address2'],
        'city': json['city'],
        'state': !exists(json, 'state') ? undefined : json['state'],
        'zip': !exists(json, 'zip') ? undefined : json['zip'],
        'email': !exists(json, 'email') ? undefined : json['email'],
        'accountNumber': !exists(json, 'accountNumber') ? undefined : json['accountNumber'],
        'officeCode': !exists(json, 'officeCode') ? undefined : json['officeCode'],
        'nonUsProvince': !exists(json, 'nonUsProvince') ? undefined : json['nonUsProvince'],
        'countryCode': json['countryCode'],
        'federalEFile': !exists(json, 'federalEFile') ? undefined : json['federalEFile'],
        'postalMail': !exists(json, 'postalMail') ? undefined : json['postalMail'],
        'stateEFile': !exists(json, 'stateEFile') ? undefined : json['stateEFile'],
        'tinMatch': !exists(json, 'tinMatch') ? undefined : json['tinMatch'],
        'noTin': !exists(json, 'noTin') ? undefined : json['noTin'],
        'secondTinNotice': !exists(json, 'secondTinNotice') ? undefined : json['secondTinNotice'],
        'addressVerification': !exists(json, 'addressVerification') ? undefined : json['addressVerification'],
        'stateAndLocalWithholding': !exists(json, 'stateAndLocalWithholding') ? undefined : StateAndLocalWithholdingRequestFromJSON(json['stateAndLocalWithholding']),
    };
}

export function FormSingleRequestBaseToJSON(value?: FormSingleRequestBase | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': value.type,
        'issuerId': value.issuerId,
        'referenceId': value.referenceId,
        'recipientTin': value.recipientTin,
        'recipientName': value.recipientName,
        'tinType': value.tinType,
        'recipientSecondName': value.recipientSecondName,
        'address': value.address,
        'address2': value.address2,
        'city': value.city,
        'state': value.state,
        'zip': value.zip,
        'email': value.email,
        'accountNumber': value.accountNumber,
        'officeCode': value.officeCode,
        'nonUsProvince': value.nonUsProvince,
        'countryCode': value.countryCode,
        'federalEFile': value.federalEFile,
        'postalMail': value.postalMail,
        'stateEFile': value.stateEFile,
        'tinMatch': value.tinMatch,
        'noTin': value.noTin,
        'secondTinNotice': value.secondTinNotice,
        'addressVerification': value.addressVerification,
        'stateAndLocalWithholding': StateAndLocalWithholdingRequestToJSON(value.stateAndLocalWithholding),
    };
}
