/* tslint:disable */
/* eslint-disable */
/**
 * Avalara 1099 & W-9 API Definition
 * ## 🔐 Authentication  Generate a **license key** from: *[Avalara Portal](https://www.avalara.com/us/en/signin.html) → Settings → License and API Keys*.  [More on authentication methods](https://developer.avalara.com/avatax-dm-combined-erp/common-setup/authentication/authentication-methods/)  [Test your credentials](https://developer.avalara.com/avatax/test-credentials/)  ## 📘 API & SDK Documentation  [Avalara SDK (.NET) on GitHub](https://github.com/avadev/Avalara-SDK-DotNet#avalarasdk--the-unified-c-library-for-next-gen-avalara-services)  [Code Examples – 1099 API](https://github.com/avadev/Avalara-SDK-DotNet/blob/main/docs/A1099/V2/Class1099IssuersApi.md#call1099issuersget)
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@avalara.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../../../runtime';
import {
    Form1099IntListItem,
    Form1099IntListItemFromJSON,
    Form1099IntListItemFromJSONTyped,
    Form1099IntListItemToJSON,
} from './Form1099IntListItem';

/**
 * 
 * @export
 * @interface Form1099IntList
 */
export interface Form1099IntList {
    /**
     * 
     * @type {Array<Form1099IntListItem>}
     * @memberof Form1099IntList
     */
    forms?: Array<Form1099IntListItem>;
    /**
     * 
     * @type {string}
     * @memberof Form1099IntList
     */
    formType?: string;
}



/**
 * Check if a given object implements the Form1099IntList interface.
 */
export function instanceOfForm1099IntList(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function Form1099IntListFromJSON(json: any): Form1099IntList {
    return Form1099IntListFromJSONTyped(json, false);
}

export function Form1099IntListFromJSONTyped(json: any, ignoreDiscriminator: boolean): Form1099IntList {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'forms': !exists(json, 'forms') ? undefined : ((json['forms'] as Array<any>)?.map(Form1099IntListItemFromJSON)),
        'formType': !exists(json, 'formType') ? undefined : json['formType'],
    };
}

export function Form1099IntListToJSON(value?: Form1099IntList | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'forms': value.forms === undefined ? undefined : ((value.forms as Array<any>)?.map(Form1099IntListItemToJSON)),
        'formType': value.formType,
    };
}
