/* tslint:disable */
/* eslint-disable */
/**
 * Avalara 1099 & W-9 API Definition
 * ## 🔐 Authentication  Generate a **license key** from: *[Avalara Portal](https://www.avalara.com/us/en/signin.html) → Settings → License and API Keys*.  [More on authentication methods](https://developer.avalara.com/avatax-dm-combined-erp/common-setup/authentication/authentication-methods/)  [Test your credentials](https://developer.avalara.com/avatax/test-credentials/)  ## 📘 API & SDK Documentation  [Avalara SDK (.NET) on GitHub](https://github.com/avadev/Avalara-SDK-DotNet#avalarasdk--the-unified-c-library-for-next-gen-avalara-services)  [Code Examples – 1099 API](https://github.com/avadev/Avalara-SDK-DotNet/blob/main/docs/A1099/V2/Class1099IssuersApi.md#call1099issuersget)
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@avalara.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../../../runtime';
import {
    Form1099StatusDetail,
    Form1099StatusDetailFromJSON,
    Form1099StatusDetailFromJSONTyped,
    Form1099StatusDetailToJSON,
} from './Form1099StatusDetail';
import {
    StateAndLocalWithholding,
    StateAndLocalWithholdingFromJSON,
    StateAndLocalWithholdingFromJSONTyped,
    StateAndLocalWithholdingToJSON,
} from './StateAndLocalWithholding';
import {
    StateEfileStatusDetail,
    StateEfileStatusDetailFromJSON,
    StateEfileStatusDetailFromJSONTyped,
    StateEfileStatusDetailToJSON,
} from './StateEfileStatusDetail';
import {
    ValidationError,
    ValidationErrorFromJSON,
    ValidationErrorFromJSONTyped,
    ValidationErrorToJSON,
} from './ValidationError';

/**
 * 
 * @export
 * @interface Form1099Div
 */
export interface Form1099Div {
    /**
     * 
     * @type {number}
     * @memberof Form1099Div
     */
    totalOrdinaryDividends?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Form1099Div
     */
    qualifiedDividends?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Form1099Div
     */
    totalCapitalGainDistributions?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Form1099Div
     */
    unrecapturedSection1250Gain?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Form1099Div
     */
    section1202Gain?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Form1099Div
     */
    collectiblesGain?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Form1099Div
     */
    section897OrdinaryDividends?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Form1099Div
     */
    section897CapitalGain?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Form1099Div
     */
    nondividendDistributions?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Form1099Div
     */
    federalIncomeTaxWithheld?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Form1099Div
     */
    section199ADividends?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Form1099Div
     */
    investmentExpenses?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Form1099Div
     */
    foreignTaxPaid?: number | null;
    /**
     * 
     * @type {string}
     * @memberof Form1099Div
     */
    foreignCountryOrUSPossession?: string | null;
    /**
     * 
     * @type {number}
     * @memberof Form1099Div
     */
    cashLiquidationDistributions?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Form1099Div
     */
    noncashLiquidationDistributions?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Form1099Div
     */
    exemptInterestDividends?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Form1099Div
     */
    specifiedPrivateActivityBondInterestDividends?: number | null;
    /**
     * 
     * @type {boolean}
     * @memberof Form1099Div
     */
    fatcaFilingRequirement?: boolean | null;
    /**
     * 
     * @type {string}
     * @memberof Form1099Div
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof Form1099Div
     */
    type?: string;
    /**
     * 
     * @type {number}
     * @memberof Form1099Div
     */
    issuerId?: number;
    /**
     * 
     * @type {string}
     * @memberof Form1099Div
     */
    issuerReferenceId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Form1099Div
     */
    issuerTin?: string | null;
    /**
     * 
     * @type {number}
     * @memberof Form1099Div
     */
    taxYear?: number;
    /**
     * 
     * @type {boolean}
     * @memberof Form1099Div
     */
    federalEfile?: boolean;
    /**
     * 
     * @type {Form1099StatusDetail}
     * @memberof Form1099Div
     */
    federalEfileStatus?: Form1099StatusDetail;
    /**
     * 
     * @type {boolean}
     * @memberof Form1099Div
     */
    stateEfile?: boolean;
    /**
     * 
     * @type {Array<StateEfileStatusDetail>}
     * @memberof Form1099Div
     */
    stateEfileStatus?: Array<StateEfileStatusDetail> | null;
    /**
     * 
     * @type {boolean}
     * @memberof Form1099Div
     */
    postalMail?: boolean;
    /**
     * 
     * @type {Form1099StatusDetail}
     * @memberof Form1099Div
     */
    postalMailStatus?: Form1099StatusDetail | null;
    /**
     * 
     * @type {boolean}
     * @memberof Form1099Div
     */
    tinMatch?: boolean;
    /**
     * 
     * @type {Form1099StatusDetail}
     * @memberof Form1099Div
     */
    tinMatchStatus?: Form1099StatusDetail | null;
    /**
     * 
     * @type {boolean}
     * @memberof Form1099Div
     */
    addressVerification?: boolean;
    /**
     * 
     * @type {Form1099StatusDetail}
     * @memberof Form1099Div
     */
    addressVerificationStatus?: Form1099StatusDetail | null;
    /**
     * 
     * @type {Form1099StatusDetail}
     * @memberof Form1099Div
     */
    eDeliveryStatus?: Form1099StatusDetail | null;
    /**
     * 
     * @type {string}
     * @memberof Form1099Div
     */
    referenceId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Form1099Div
     */
    email?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Form1099Div
     */
    tinType?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Form1099Div
     */
    tin?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof Form1099Div
     */
    noTin?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Form1099Div
     */
    secondTinNotice?: boolean | null;
    /**
     * 
     * @type {string}
     * @memberof Form1099Div
     */
    recipientName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Form1099Div
     */
    recipientSecondName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Form1099Div
     */
    address?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Form1099Div
     */
    address2?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Form1099Div
     */
    city?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Form1099Div
     */
    state?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Form1099Div
     */
    zip?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Form1099Div
     */
    nonUsProvince?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Form1099Div
     */
    countryCode?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Form1099Div
     */
    accountNumber?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Form1099Div
     */
    officeCode?: string | null;
    /**
     * 
     * @type {Array<ValidationError>}
     * @memberof Form1099Div
     */
    validationErrors?: Array<ValidationError> | null;
    /**
     * 
     * @type {Date}
     * @memberof Form1099Div
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof Form1099Div
     */
    updatedAt?: Date;
    /**
     * 
     * @type {StateAndLocalWithholding}
     * @memberof Form1099Div
     */
    stateAndLocalWithholding?: StateAndLocalWithholding | null;
}



/**
 * Check if a given object implements the Form1099Div interface.
 */
export function instanceOfForm1099Div(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function Form1099DivFromJSON(json: any): Form1099Div {
    return Form1099DivFromJSONTyped(json, false);
}

export function Form1099DivFromJSONTyped(json: any, ignoreDiscriminator: boolean): Form1099Div {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'totalOrdinaryDividends': !exists(json, 'totalOrdinaryDividends') ? undefined : json['totalOrdinaryDividends'],
        'qualifiedDividends': !exists(json, 'qualifiedDividends') ? undefined : json['qualifiedDividends'],
        'totalCapitalGainDistributions': !exists(json, 'totalCapitalGainDistributions') ? undefined : json['totalCapitalGainDistributions'],
        'unrecapturedSection1250Gain': !exists(json, 'unrecapturedSection1250Gain') ? undefined : json['unrecapturedSection1250Gain'],
        'section1202Gain': !exists(json, 'section1202Gain') ? undefined : json['section1202Gain'],
        'collectiblesGain': !exists(json, 'collectiblesGain') ? undefined : json['collectiblesGain'],
        'section897OrdinaryDividends': !exists(json, 'section897OrdinaryDividends') ? undefined : json['section897OrdinaryDividends'],
        'section897CapitalGain': !exists(json, 'section897CapitalGain') ? undefined : json['section897CapitalGain'],
        'nondividendDistributions': !exists(json, 'nondividendDistributions') ? undefined : json['nondividendDistributions'],
        'federalIncomeTaxWithheld': !exists(json, 'federalIncomeTaxWithheld') ? undefined : json['federalIncomeTaxWithheld'],
        'section199ADividends': !exists(json, 'section199ADividends') ? undefined : json['section199ADividends'],
        'investmentExpenses': !exists(json, 'investmentExpenses') ? undefined : json['investmentExpenses'],
        'foreignTaxPaid': !exists(json, 'foreignTaxPaid') ? undefined : json['foreignTaxPaid'],
        'foreignCountryOrUSPossession': !exists(json, 'foreignCountryOrUSPossession') ? undefined : json['foreignCountryOrUSPossession'],
        'cashLiquidationDistributions': !exists(json, 'cashLiquidationDistributions') ? undefined : json['cashLiquidationDistributions'],
        'noncashLiquidationDistributions': !exists(json, 'noncashLiquidationDistributions') ? undefined : json['noncashLiquidationDistributions'],
        'exemptInterestDividends': !exists(json, 'exemptInterestDividends') ? undefined : json['exemptInterestDividends'],
        'specifiedPrivateActivityBondInterestDividends': !exists(json, 'specifiedPrivateActivityBondInterestDividends') ? undefined : json['specifiedPrivateActivityBondInterestDividends'],
        'fatcaFilingRequirement': !exists(json, 'fatcaFilingRequirement') ? undefined : json['fatcaFilingRequirement'],
        'id': !exists(json, 'id') ? undefined : json['id'],
        'type': !exists(json, 'type') ? undefined : json['type'],
        'issuerId': !exists(json, 'issuerId') ? undefined : json['issuerId'],
        'issuerReferenceId': !exists(json, 'issuerReferenceId') ? undefined : json['issuerReferenceId'],
        'issuerTin': !exists(json, 'issuerTin') ? undefined : json['issuerTin'],
        'taxYear': !exists(json, 'taxYear') ? undefined : json['taxYear'],
        'federalEfile': !exists(json, 'federalEfile') ? undefined : json['federalEfile'],
        'federalEfileStatus': !exists(json, 'federalEfileStatus') ? undefined : Form1099StatusDetailFromJSON(json['federalEfileStatus']),
        'stateEfile': !exists(json, 'stateEfile') ? undefined : json['stateEfile'],
        'stateEfileStatus': !exists(json, 'stateEfileStatus') ? undefined : (json['stateEfileStatus'] === null ? null : (json['stateEfileStatus'] as Array<any>)?.map(StateEfileStatusDetailFromJSON)),
        'postalMail': !exists(json, 'postalMail') ? undefined : json['postalMail'],
        'postalMailStatus': !exists(json, 'postalMailStatus') ? undefined : Form1099StatusDetailFromJSON(json['postalMailStatus']),
        'tinMatch': !exists(json, 'tinMatch') ? undefined : json['tinMatch'],
        'tinMatchStatus': !exists(json, 'tinMatchStatus') ? undefined : Form1099StatusDetailFromJSON(json['tinMatchStatus']),
        'addressVerification': !exists(json, 'addressVerification') ? undefined : json['addressVerification'],
        'addressVerificationStatus': !exists(json, 'addressVerificationStatus') ? undefined : Form1099StatusDetailFromJSON(json['addressVerificationStatus']),
        'eDeliveryStatus': !exists(json, 'eDeliveryStatus') ? undefined : Form1099StatusDetailFromJSON(json['eDeliveryStatus']),
        'referenceId': !exists(json, 'referenceId') ? undefined : json['referenceId'],
        'email': !exists(json, 'email') ? undefined : json['email'],
        'tinType': !exists(json, 'tinType') ? undefined : json['tinType'],
        'tin': !exists(json, 'tin') ? undefined : json['tin'],
        'noTin': !exists(json, 'noTin') ? undefined : json['noTin'],
        'secondTinNotice': !exists(json, 'secondTinNotice') ? undefined : json['secondTinNotice'],
        'recipientName': !exists(json, 'recipientName') ? undefined : json['recipientName'],
        'recipientSecondName': !exists(json, 'recipientSecondName') ? undefined : json['recipientSecondName'],
        'address': !exists(json, 'address') ? undefined : json['address'],
        'address2': !exists(json, 'address2') ? undefined : json['address2'],
        'city': !exists(json, 'city') ? undefined : json['city'],
        'state': !exists(json, 'state') ? undefined : json['state'],
        'zip': !exists(json, 'zip') ? undefined : json['zip'],
        'nonUsProvince': !exists(json, 'nonUsProvince') ? undefined : json['nonUsProvince'],
        'countryCode': !exists(json, 'countryCode') ? undefined : json['countryCode'],
        'accountNumber': !exists(json, 'accountNumber') ? undefined : json['accountNumber'],
        'officeCode': !exists(json, 'officeCode') ? undefined : json['officeCode'],
        'validationErrors': !exists(json, 'validationErrors') ? undefined : (json['validationErrors'] === null ? null : (json['validationErrors'] as Array<any>)?.map(ValidationErrorFromJSON)),
        'createdAt': !exists(json, 'createdAt') ? undefined : (new Date(json['createdAt'])),
        'updatedAt': !exists(json, 'updatedAt') ? undefined : (new Date(json['updatedAt'])),
        'stateAndLocalWithholding': !exists(json, 'stateAndLocalWithholding') ? undefined : StateAndLocalWithholdingFromJSON(json['stateAndLocalWithholding']),
    };
}

export function Form1099DivToJSON(value?: Form1099Div | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'totalOrdinaryDividends': value.totalOrdinaryDividends,
        'qualifiedDividends': value.qualifiedDividends,
        'totalCapitalGainDistributions': value.totalCapitalGainDistributions,
        'unrecapturedSection1250Gain': value.unrecapturedSection1250Gain,
        'section1202Gain': value.section1202Gain,
        'collectiblesGain': value.collectiblesGain,
        'section897OrdinaryDividends': value.section897OrdinaryDividends,
        'section897CapitalGain': value.section897CapitalGain,
        'nondividendDistributions': value.nondividendDistributions,
        'federalIncomeTaxWithheld': value.federalIncomeTaxWithheld,
        'section199ADividends': value.section199ADividends,
        'investmentExpenses': value.investmentExpenses,
        'foreignTaxPaid': value.foreignTaxPaid,
        'foreignCountryOrUSPossession': value.foreignCountryOrUSPossession,
        'cashLiquidationDistributions': value.cashLiquidationDistributions,
        'noncashLiquidationDistributions': value.noncashLiquidationDistributions,
        'exemptInterestDividends': value.exemptInterestDividends,
        'specifiedPrivateActivityBondInterestDividends': value.specifiedPrivateActivityBondInterestDividends,
        'fatcaFilingRequirement': value.fatcaFilingRequirement,
        'id': value.id,
        'type': value.type,
        'issuerId': value.issuerId,
        'issuerReferenceId': value.issuerReferenceId,
        'issuerTin': value.issuerTin,
        'taxYear': value.taxYear,
        'federalEfile': value.federalEfile,
        'federalEfileStatus': Form1099StatusDetailToJSON(value.federalEfileStatus),
        'stateEfile': value.stateEfile,
        'stateEfileStatus': value.stateEfileStatus === undefined ? undefined : (value.stateEfileStatus === null ? null : (value.stateEfileStatus as Array<any>)?.map(StateEfileStatusDetailToJSON)),
        'postalMail': value.postalMail,
        'postalMailStatus': Form1099StatusDetailToJSON(value.postalMailStatus),
        'tinMatch': value.tinMatch,
        'tinMatchStatus': Form1099StatusDetailToJSON(value.tinMatchStatus),
        'addressVerification': value.addressVerification,
        'addressVerificationStatus': Form1099StatusDetailToJSON(value.addressVerificationStatus),
        'eDeliveryStatus': Form1099StatusDetailToJSON(value.eDeliveryStatus),
        'referenceId': value.referenceId,
        'email': value.email,
        'tinType': value.tinType,
        'tin': value.tin,
        'noTin': value.noTin,
        'secondTinNotice': value.secondTinNotice,
        'recipientName': value.recipientName,
        'recipientSecondName': value.recipientSecondName,
        'address': value.address,
        'address2': value.address2,
        'city': value.city,
        'state': value.state,
        'zip': value.zip,
        'nonUsProvince': value.nonUsProvince,
        'countryCode': value.countryCode,
        'accountNumber': value.accountNumber,
        'officeCode': value.officeCode,
        'validationErrors': value.validationErrors === undefined ? undefined : (value.validationErrors === null ? null : (value.validationErrors as Array<any>)?.map(ValidationErrorToJSON)),
        'createdAt': value.createdAt === undefined ? undefined : (value.createdAt.toISOString()),
        'updatedAt': value.updatedAt === undefined ? undefined : (value.updatedAt.toISOString()),
        'stateAndLocalWithholding': StateAndLocalWithholdingToJSON(value.stateAndLocalWithholding),
    };
}
