/* tslint:disable */
/* eslint-disable */
/**
 * Avalara 1099 & W-9 API Definition
 * ## 🔐 Authentication  Use **username/password** or generate a **license key** from: *Avalara Portal → Settings → License and API Keys*.  [More on authentication methods](https://developer.avalara.com/avatax-dm-combined-erp/common-setup/authentication/authentication-methods/)  [Test your credentials](https://developer.avalara.com/avatax/test-credentials/)  ## 📘 API & SDK Documentation  [Avalara SDK (.NET) on GitHub](https://github.com/avadev/Avalara-SDK-DotNet#avalarasdk--the-unified-c-library-for-next-gen-avalara-services)  [Code Examples – 1099 API](https://github.com/avadev/Avalara-SDK-DotNet/blob/main/docs/A1099/V2/Class1099IssuersApi.md#call1099issuersget)
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@avalara.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../../../runtime';
/**
 * 
 * @export
 * @interface FormResponseBase
 */
export interface FormResponseBase {
    /**
     * 
     * @type {string}
     * @memberof FormResponseBase
     */
    issuerId?: string;
    /**
     * 
     * @type {string}
     * @memberof FormResponseBase
     */
    issuerReferenceId?: string;
    /**
     * 
     * @type {string}
     * @memberof FormResponseBase
     */
    issuerTin?: string;
    /**
     * 
     * @type {number}
     * @memberof FormResponseBase
     */
    taxYear?: number;
    /**
     * 
     * @type {string}
     * @memberof FormResponseBase
     */
    referenceId?: string;
    /**
     * 
     * @type {string}
     * @memberof FormResponseBase
     */
    recipientName?: string;
    /**
     * 
     * @type {string}
     * @memberof FormResponseBase
     */
    recipientFederalId?: string;
    /**
     * 
     * @type {number}
     * @memberof FormResponseBase
     */
    federalIdType?: number;
    /**
     * 
     * @type {string}
     * @memberof FormResponseBase
     */
    recipientSecondName?: string;
    /**
     * 
     * @type {string}
     * @memberof FormResponseBase
     */
    streetAddress?: string;
    /**
     * 
     * @type {string}
     * @memberof FormResponseBase
     */
    streetAddressLine2?: string;
    /**
     * 
     * @type {string}
     * @memberof FormResponseBase
     */
    city?: string;
    /**
     * 
     * @type {string}
     * @memberof FormResponseBase
     */
    state?: string;
    /**
     * 
     * @type {string}
     * @memberof FormResponseBase
     */
    zip?: string;
    /**
     * 
     * @type {string}
     * @memberof FormResponseBase
     */
    recipientEmail?: string;
    /**
     * 
     * @type {string}
     * @memberof FormResponseBase
     */
    accountNumber?: string;
    /**
     * 
     * @type {string}
     * @memberof FormResponseBase
     */
    officeCode?: string;
    /**
     * 
     * @type {string}
     * @memberof FormResponseBase
     */
    recipientNonUsProvince?: string;
    /**
     * 
     * @type {string}
     * @memberof FormResponseBase
     */
    countryCode?: string;
}



/**
 * Check if a given object implements the FormResponseBase interface.
 */
export function instanceOfFormResponseBase(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function FormResponseBaseFromJSON(json: any): FormResponseBase {
    return FormResponseBaseFromJSONTyped(json, false);
}

export function FormResponseBaseFromJSONTyped(json: any, ignoreDiscriminator: boolean): FormResponseBase {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'issuerId': !exists(json, 'issuerId') ? undefined : json['issuerId'],
        'issuerReferenceId': !exists(json, 'issuerReferenceId') ? undefined : json['issuerReferenceId'],
        'issuerTin': !exists(json, 'issuerTin') ? undefined : json['issuerTin'],
        'taxYear': !exists(json, 'taxYear') ? undefined : json['taxYear'],
        'referenceId': !exists(json, 'referenceId') ? undefined : json['referenceId'],
        'recipientName': !exists(json, 'recipientName') ? undefined : json['recipientName'],
        'recipientFederalId': !exists(json, 'recipientFederalId') ? undefined : json['recipientFederalId'],
        'federalIdType': !exists(json, 'federalIdType') ? undefined : json['federalIdType'],
        'recipientSecondName': !exists(json, 'recipientSecondName') ? undefined : json['recipientSecondName'],
        'streetAddress': !exists(json, 'streetAddress') ? undefined : json['streetAddress'],
        'streetAddressLine2': !exists(json, 'streetAddressLine2') ? undefined : json['streetAddressLine2'],
        'city': !exists(json, 'city') ? undefined : json['city'],
        'state': !exists(json, 'state') ? undefined : json['state'],
        'zip': !exists(json, 'zip') ? undefined : json['zip'],
        'recipientEmail': !exists(json, 'recipientEmail') ? undefined : json['recipientEmail'],
        'accountNumber': !exists(json, 'accountNumber') ? undefined : json['accountNumber'],
        'officeCode': !exists(json, 'officeCode') ? undefined : json['officeCode'],
        'recipientNonUsProvince': !exists(json, 'recipientNonUsProvince') ? undefined : json['recipientNonUsProvince'],
        'countryCode': !exists(json, 'countryCode') ? undefined : json['countryCode'],
    };
}

export function FormResponseBaseToJSON(value?: FormResponseBase | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'issuerId': value.issuerId,
        'issuerReferenceId': value.issuerReferenceId,
        'issuerTin': value.issuerTin,
        'taxYear': value.taxYear,
        'referenceId': value.referenceId,
        'recipientName': value.recipientName,
        'recipientFederalId': value.recipientFederalId,
        'federalIdType': value.federalIdType,
        'recipientSecondName': value.recipientSecondName,
        'streetAddress': value.streetAddress,
        'streetAddressLine2': value.streetAddressLine2,
        'city': value.city,
        'state': value.state,
        'zip': value.zip,
        'recipientEmail': value.recipientEmail,
        'accountNumber': value.accountNumber,
        'officeCode': value.officeCode,
        'recipientNonUsProvince': value.recipientNonUsProvince,
        'countryCode': value.countryCode,
    };
}
