/* tslint:disable */
/* eslint-disable */
/**
 * Avalara 1099 & W-9 API Definition
 * ## 🔐 Authentication  Use **username/password** or generate a **license key** from: *Avalara Portal → Settings → License and API Keys*.  [More on authentication methods](https://developer.avalara.com/avatax-dm-combined-erp/common-setup/authentication/authentication-methods/)  [Test your credentials](https://developer.avalara.com/avatax/test-credentials/)  ## 📘 API & SDK Documentation  [Avalara SDK (.NET) on GitHub](https://github.com/avadev/Avalara-SDK-DotNet#avalarasdk--the-unified-c-library-for-next-gen-avalara-services)  [Code Examples – 1099 API](https://github.com/avadev/Avalara-SDK-DotNet/blob/main/docs/A1099/V2/Class1099IssuersApi.md#call1099issuersget)
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@avalara.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../../../runtime';
import {
    StateAndLocalWithholdingResponse,
    StateAndLocalWithholdingResponseFromJSON,
    StateAndLocalWithholdingResponseFromJSONTyped,
    StateAndLocalWithholdingResponseToJSON,
} from './StateAndLocalWithholdingResponse';
import {
    StateEfileStatusDetailApp,
    StateEfileStatusDetailAppFromJSON,
    StateEfileStatusDetailAppFromJSONTyped,
    StateEfileStatusDetailAppToJSON,
} from './StateEfileStatusDetailApp';
import {
    StatusDetail,
    StatusDetailFromJSON,
    StatusDetailFromJSONTyped,
    StatusDetailToJSON,
} from './StatusDetail';
import {
    ValidationErrorApp,
    ValidationErrorAppFromJSON,
    ValidationErrorAppFromJSONTyped,
    ValidationErrorAppToJSON,
} from './ValidationErrorApp';

/**
 * 
 * @export
 * @interface Form1099DivResponse
 */
export interface Form1099DivResponse {
    /**
     * 
     * @type {string}
     * @memberof Form1099DivResponse
     */
    readonly type?: Form1099DivResponseTypeEnum;
    /**
     * 
     * @type {Date}
     * @memberof Form1099DivResponse
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof Form1099DivResponse
     */
    updatedAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof Form1099DivResponse
     */
    userId?: string;
    /**
     * 
     * @type {StateAndLocalWithholdingResponse}
     * @memberof Form1099DivResponse
     */
    stateAndLocalWithholding?: StateAndLocalWithholdingResponse;
    /**
     * 
     * @type {string}
     * @memberof Form1099DivResponse
     */
    tinType?: Form1099DivResponseTinTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof Form1099DivResponse
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof Form1099DivResponse
     */
    issuerId?: string;
    /**
     * 
     * @type {string}
     * @memberof Form1099DivResponse
     */
    issuerReferenceId?: string;
    /**
     * 
     * @type {string}
     * @memberof Form1099DivResponse
     */
    issuerTin?: string;
    /**
     * 
     * @type {number}
     * @memberof Form1099DivResponse
     */
    taxYear?: number;
    /**
     * 
     * @type {string}
     * @memberof Form1099DivResponse
     */
    referenceId?: string;
    /**
     * 
     * @type {string}
     * @memberof Form1099DivResponse
     */
    recipientName?: string;
    /**
     * 
     * @type {string}
     * @memberof Form1099DivResponse
     */
    recipientTin?: string;
    /**
     * 
     * @type {string}
     * @memberof Form1099DivResponse
     */
    recipientSecondName?: string;
    /**
     * 
     * @type {string}
     * @memberof Form1099DivResponse
     */
    address?: string;
    /**
     * 
     * @type {string}
     * @memberof Form1099DivResponse
     */
    address2?: string;
    /**
     * 
     * @type {string}
     * @memberof Form1099DivResponse
     */
    city?: string;
    /**
     * 
     * @type {string}
     * @memberof Form1099DivResponse
     */
    state?: string;
    /**
     * 
     * @type {string}
     * @memberof Form1099DivResponse
     */
    zip?: string;
    /**
     * 
     * @type {string}
     * @memberof Form1099DivResponse
     */
    recipientEmail?: string;
    /**
     * 
     * @type {string}
     * @memberof Form1099DivResponse
     */
    accountNumber?: string;
    /**
     * 
     * @type {string}
     * @memberof Form1099DivResponse
     */
    officeCode?: string;
    /**
     * 
     * @type {string}
     * @memberof Form1099DivResponse
     */
    recipientNonUsProvince?: string;
    /**
     * 
     * @type {string}
     * @memberof Form1099DivResponse
     */
    countryCode?: string;
    /**
     * 
     * @type {boolean}
     * @memberof Form1099DivResponse
     */
    federalEFile?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Form1099DivResponse
     */
    postalMail?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Form1099DivResponse
     */
    stateEFile?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Form1099DivResponse
     */
    tinMatch?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Form1099DivResponse
     */
    addressVerification?: boolean;
    /**
     * 
     * @type {StatusDetail}
     * @memberof Form1099DivResponse
     */
    federalEfileStatus?: StatusDetail | null;
    /**
     * 
     * @type {Array<StateEfileStatusDetailApp>}
     * @memberof Form1099DivResponse
     */
    stateEfileStatus?: Array<StateEfileStatusDetailApp> | null;
    /**
     * 
     * @type {StatusDetail}
     * @memberof Form1099DivResponse
     */
    postalMailStatus?: StatusDetail | null;
    /**
     * 
     * @type {StatusDetail}
     * @memberof Form1099DivResponse
     */
    tinMatchStatus?: StatusDetail | null;
    /**
     * 
     * @type {StatusDetail}
     * @memberof Form1099DivResponse
     */
    addressVerificationStatus?: StatusDetail | null;
    /**
     * 
     * @type {Array<ValidationErrorApp>}
     * @memberof Form1099DivResponse
     */
    validationErrors?: Array<ValidationErrorApp> | null;
}

/**
* @export
* @enum {string}
*/
export enum Form1099DivResponseTypeEnum {
    Form1099Nec = 'Form1099Nec',
    Form1099Misc = 'Form1099Misc',
    Form1099Div = 'Form1099Div',
    Form1099R = 'Form1099R',
    Form1099K = 'Form1099K',
    Form1095B = 'Form1095B'
}/**
* @export
* @enum {string}
*/
export enum Form1099DivResponseTinTypeEnum {
    Ein = 'EIN',
    Ssn = 'SSN',
    Itin = 'ITIN',
    Atin = 'ATIN'
}

/**
 * Check if a given object implements the Form1099DivResponse interface.
 */
export function instanceOfForm1099DivResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function Form1099DivResponseFromJSON(json: any): Form1099DivResponse {
    return Form1099DivResponseFromJSONTyped(json, false);
}

export function Form1099DivResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): Form1099DivResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': !exists(json, 'type') ? undefined : json['type'],
        'createdAt': !exists(json, 'createdAt') ? undefined : (new Date(json['createdAt'])),
        'updatedAt': !exists(json, 'updatedAt') ? undefined : (new Date(json['updatedAt'])),
        'userId': !exists(json, 'userId') ? undefined : json['userId'],
        'stateAndLocalWithholding': !exists(json, 'stateAndLocalWithholding') ? undefined : StateAndLocalWithholdingResponseFromJSON(json['stateAndLocalWithholding']),
        'tinType': !exists(json, 'tinType') ? undefined : json['tinType'],
        'id': !exists(json, 'id') ? undefined : json['id'],
        'issuerId': !exists(json, 'issuerId') ? undefined : json['issuerId'],
        'issuerReferenceId': !exists(json, 'issuerReferenceId') ? undefined : json['issuerReferenceId'],
        'issuerTin': !exists(json, 'issuerTin') ? undefined : json['issuerTin'],
        'taxYear': !exists(json, 'taxYear') ? undefined : json['taxYear'],
        'referenceId': !exists(json, 'referenceId') ? undefined : json['referenceId'],
        'recipientName': !exists(json, 'recipientName') ? undefined : json['recipientName'],
        'recipientTin': !exists(json, 'recipientTin') ? undefined : json['recipientTin'],
        'recipientSecondName': !exists(json, 'recipientSecondName') ? undefined : json['recipientSecondName'],
        'address': !exists(json, 'address') ? undefined : json['address'],
        'address2': !exists(json, 'address2') ? undefined : json['address2'],
        'city': !exists(json, 'city') ? undefined : json['city'],
        'state': !exists(json, 'state') ? undefined : json['state'],
        'zip': !exists(json, 'zip') ? undefined : json['zip'],
        'recipientEmail': !exists(json, 'recipientEmail') ? undefined : json['recipientEmail'],
        'accountNumber': !exists(json, 'accountNumber') ? undefined : json['accountNumber'],
        'officeCode': !exists(json, 'officeCode') ? undefined : json['officeCode'],
        'recipientNonUsProvince': !exists(json, 'recipientNonUsProvince') ? undefined : json['recipientNonUsProvince'],
        'countryCode': !exists(json, 'countryCode') ? undefined : json['countryCode'],
        'federalEFile': !exists(json, 'federalEFile') ? undefined : json['federalEFile'],
        'postalMail': !exists(json, 'postalMail') ? undefined : json['postalMail'],
        'stateEFile': !exists(json, 'stateEFile') ? undefined : json['stateEFile'],
        'tinMatch': !exists(json, 'tinMatch') ? undefined : json['tinMatch'],
        'addressVerification': !exists(json, 'addressVerification') ? undefined : json['addressVerification'],
        'federalEfileStatus': !exists(json, 'federalEfileStatus') ? undefined : StatusDetailFromJSON(json['federalEfileStatus']),
        'stateEfileStatus': !exists(json, 'stateEfileStatus') ? undefined : (json['stateEfileStatus'] === null ? null : (json['stateEfileStatus'] as Array<any>)?.map(StateEfileStatusDetailAppFromJSON)),
        'postalMailStatus': !exists(json, 'postalMailStatus') ? undefined : StatusDetailFromJSON(json['postalMailStatus']),
        'tinMatchStatus': !exists(json, 'tinMatchStatus') ? undefined : StatusDetailFromJSON(json['tinMatchStatus']),
        'addressVerificationStatus': !exists(json, 'addressVerificationStatus') ? undefined : StatusDetailFromJSON(json['addressVerificationStatus']),
        'validationErrors': !exists(json, 'validationErrors') ? undefined : (json['validationErrors'] === null ? null : (json['validationErrors'] as Array<any>)?.map(ValidationErrorAppFromJSON)),
    };
}

export function Form1099DivResponseToJSON(value?: Form1099DivResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'createdAt': value.createdAt === undefined ? undefined : (value.createdAt.toISOString()),
        'updatedAt': value.updatedAt === undefined ? undefined : (value.updatedAt.toISOString()),
        'userId': value.userId,
        'stateAndLocalWithholding': StateAndLocalWithholdingResponseToJSON(value.stateAndLocalWithholding),
        'tinType': value.tinType,
        'id': value.id,
        'issuerId': value.issuerId,
        'issuerReferenceId': value.issuerReferenceId,
        'issuerTin': value.issuerTin,
        'taxYear': value.taxYear,
        'referenceId': value.referenceId,
        'recipientName': value.recipientName,
        'recipientTin': value.recipientTin,
        'recipientSecondName': value.recipientSecondName,
        'address': value.address,
        'address2': value.address2,
        'city': value.city,
        'state': value.state,
        'zip': value.zip,
        'recipientEmail': value.recipientEmail,
        'accountNumber': value.accountNumber,
        'officeCode': value.officeCode,
        'recipientNonUsProvince': value.recipientNonUsProvince,
        'countryCode': value.countryCode,
        'federalEFile': value.federalEFile,
        'postalMail': value.postalMail,
        'stateEFile': value.stateEFile,
        'tinMatch': value.tinMatch,
        'addressVerification': value.addressVerification,
        'federalEfileStatus': StatusDetailToJSON(value.federalEfileStatus),
        'stateEfileStatus': value.stateEfileStatus === undefined ? undefined : (value.stateEfileStatus === null ? null : (value.stateEfileStatus as Array<any>)?.map(StateEfileStatusDetailAppToJSON)),
        'postalMailStatus': StatusDetailToJSON(value.postalMailStatus),
        'tinMatchStatus': StatusDetailToJSON(value.tinMatchStatus),
        'addressVerificationStatus': StatusDetailToJSON(value.addressVerificationStatus),
        'validationErrors': value.validationErrors === undefined ? undefined : (value.validationErrors === null ? null : (value.validationErrors as Array<any>)?.map(ValidationErrorAppToJSON)),
    };
}
