/* tslint:disable */
/* eslint-disable */
/**
 * Avalara 1099 & W-9 API Definition
 * ## 🔐 Authentication  Use **username/password** or generate a **license key** from: *Avalara Portal → Settings → License and API Keys*.  [More on authentication methods](https://developer.avalara.com/avatax-dm-combined-erp/common-setup/authentication/authentication-methods/)  [Test your credentials](https://developer.avalara.com/avatax/test-credentials/)  ## 📘 API & SDK Documentation  [Avalara SDK (.NET) on GitHub](https://github.com/avadev/Avalara-SDK-DotNet#avalarasdk--the-unified-c-library-for-next-gen-avalara-services)  [Code Examples – 1099 API](https://github.com/avadev/Avalara-SDK-DotNet/blob/main/docs/A1099/V2/Class1099IssuersApi.md#call1099issuersget)
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@avalara.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../../../runtime';
/**
 * 
 * @export
 * @interface IssuerResponse
 */
export interface IssuerResponse {
    /**
     * Unique identifier set when the record is created
     * @type {string}
     * @memberof IssuerResponse
     */
    readonly id?: string;
    /**
     * Legal name, not DBA
     * @type {string}
     * @memberof IssuerResponse
     */
    name?: string;
    /**
     * Optional DBA name or continuation of a long legal name
     * @type {string}
     * @memberof IssuerResponse
     */
    nameDba?: string;
    /**
     * Tax identification number
     * @type {string}
     * @memberof IssuerResponse
     */
    tin?: string;
    /**
     * Optional identifier for your reference, never shown to any agency or recipient.
     * We will also prefix download filenames with this value, if present.
     * Can only include letters, numbers, dashes, underscores and spaces.
     * @type {string}
     * @memberof IssuerResponse
     */
    referenceId?: string;
    /**
     * Telephone number
     * @type {string}
     * @memberof IssuerResponse
     */
    telephone?: string;
    /**
     * Tax year
     * @type {number}
     * @memberof IssuerResponse
     */
    taxYear?: number | null;
    /**
     * If there is a transfer agent, use the address of the transfer agent.
     * @type {string}
     * @memberof IssuerResponse
     */
    countryCode?: string | null;
    /**
     * Email address
     * @type {string}
     * @memberof IssuerResponse
     */
    email?: string | null;
    /**
     * Address
     * @type {string}
     * @memberof IssuerResponse
     */
    address?: string | null;
    /**
     * City
     * @type {string}
     * @memberof IssuerResponse
     */
    city?: string | null;
    /**
     * State
     * @type {string}
     * @memberof IssuerResponse
     */
    state?: string | null;
    /**
     * Zip code
     * @type {string}
     * @memberof IssuerResponse
     */
    zip?: string | null;
    /**
     * Foreign province
     * @type {string}
     * @memberof IssuerResponse
     */
    foreignProvince?: string | null;
    /**
     * Transfer Agent's Name
     * @type {string}
     * @memberof IssuerResponse
     */
    transferAgentName?: string | null;
    /**
     * Last year of filing for this payer
     * @type {boolean}
     * @memberof IssuerResponse
     */
    lastFiling?: boolean;
    /**
     * Date time when the issuer was created
     * @type {Date}
     * @memberof IssuerResponse
     */
    readonly createdAt?: Date;
    /**
     * Date time when the issuer was updated
     * @type {Date}
     * @memberof IssuerResponse
     */
    readonly updatedAt?: Date;
}



/**
 * Check if a given object implements the IssuerResponse interface.
 */
export function instanceOfIssuerResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function IssuerResponseFromJSON(json: any): IssuerResponse {
    return IssuerResponseFromJSONTyped(json, false);
}

export function IssuerResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): IssuerResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'nameDba': !exists(json, 'nameDba') ? undefined : json['nameDba'],
        'tin': !exists(json, 'tin') ? undefined : json['tin'],
        'referenceId': !exists(json, 'referenceId') ? undefined : json['referenceId'],
        'telephone': !exists(json, 'telephone') ? undefined : json['telephone'],
        'taxYear': !exists(json, 'taxYear') ? undefined : json['taxYear'],
        'countryCode': !exists(json, 'countryCode') ? undefined : json['countryCode'],
        'email': !exists(json, 'email') ? undefined : json['email'],
        'address': !exists(json, 'address') ? undefined : json['address'],
        'city': !exists(json, 'city') ? undefined : json['city'],
        'state': !exists(json, 'state') ? undefined : json['state'],
        'zip': !exists(json, 'zip') ? undefined : json['zip'],
        'foreignProvince': !exists(json, 'foreignProvince') ? undefined : json['foreignProvince'],
        'transferAgentName': !exists(json, 'transferAgentName') ? undefined : json['transferAgentName'],
        'lastFiling': !exists(json, 'lastFiling') ? undefined : json['lastFiling'],
        'createdAt': !exists(json, 'createdAt') ? undefined : (new Date(json['createdAt'])),
        'updatedAt': !exists(json, 'updatedAt') ? undefined : (new Date(json['updatedAt'])),
    };
}

export function IssuerResponseToJSON(value?: IssuerResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'nameDba': value.nameDba,
        'tin': value.tin,
        'referenceId': value.referenceId,
        'telephone': value.telephone,
        'taxYear': value.taxYear,
        'countryCode': value.countryCode,
        'email': value.email,
        'address': value.address,
        'city': value.city,
        'state': value.state,
        'zip': value.zip,
        'foreignProvince': value.foreignProvince,
        'transferAgentName': value.transferAgentName,
        'lastFiling': value.lastFiling,
    };
}
