/* tslint:disable */
/* eslint-disable */
/**
 * Avalara 1099 & W-9 API Definition
 * ## 🔐 Authentication  Generate a **license key** from: *[Avalara Portal](https://www.avalara.com/us/en/signin.html) → Settings → License and API Keys*.  [More on authentication methods](https://developer.avalara.com/avatax-dm-combined-erp/common-setup/authentication/authentication-methods/)  [Test your credentials](https://developer.avalara.com/avatax/test-credentials/)  ## 📘 API & SDK Documentation  [Avalara SDK (.NET) on GitHub](https://github.com/avadev/Avalara-SDK-DotNet#avalarasdk--the-unified-c-library-for-next-gen-avalara-services)  [Code Examples – 1099 API](https://github.com/avadev/Avalara-SDK-DotNet/blob/main/docs/A1099/V2/Class1099IssuersApi.md#call1099issuersget)
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@avalara.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../../../runtime';
/**
 * 
 * @export
 * @interface IssuerBase
 */
export interface IssuerBase {
    /**
     * Legal name. Not the DBA name.
     * @type {string}
     * @memberof IssuerBase
     */
    name: string | null;
    /**
     * Doing Business As (DBA) name or continuation of a long legal name. Use either this or 'transferAgentName'.
     * @type {string}
     * @memberof IssuerBase
     */
    dbaName?: string | null;
    /**
     * Federal Tax Identification Number (TIN).
     * @type {string}
     * @memberof IssuerBase
     */
    tin?: string | null;
    /**
     * Internal reference ID. Never shown to any agency or recipient. If present, it will prefix download filenames. Allowed characters: letters, numbers, dashes, underscores, and spaces.
     * @type {string}
     * @memberof IssuerBase
     */
    referenceId?: string | null;
    /**
     * Contact phone number (must contain at least 10 digits, max 15 characters). For recipient inquiries.
     * @type {string}
     * @memberof IssuerBase
     */
    telephone: string | null;
    /**
     * Tax year for which the forms are being filed (e.g., 2024). Must be within current tax year and current tax year - 4. It's only required on creation, and cannot be modified on update.
     * @type {number}
     * @memberof IssuerBase
     */
    taxYear: number | null;
    /**
     * Two-letter IRS country code (e.g., 'US', 'CA'), as defined at https://www.irs.gov/e-file-providers/country-codes. If there is a transfer agent, use the transfer agent's shipping address.
     * @type {string}
     * @memberof IssuerBase
     */
    countryCode: string | null;
    /**
     * Contact email address. For recipient inquiries. Phone will be used on communications if you don't specify an email
     * @type {string}
     * @memberof IssuerBase
     */
    email?: string | null;
    /**
     * Address.
     * @type {string}
     * @memberof IssuerBase
     */
    address: string | null;
    /**
     * City.
     * @type {string}
     * @memberof IssuerBase
     */
    city: string | null;
    /**
     * Two-letter US state or Canadian province code (required for US/CA addresses).
     * @type {string}
     * @memberof IssuerBase
     */
    state: string | null;
    /**
     * ZIP/postal code.
     * @type {string}
     * @memberof IssuerBase
     */
    zip: string | null;
    /**
     * Province or region for non-US/CA addresses.
     * @type {string}
     * @memberof IssuerBase
     */
    foreignProvince?: string | null;
    /**
     * Name of the transfer agent, if applicable — optional; use either this or 'dbaName'.
     * @type {string}
     * @memberof IssuerBase
     */
    transferAgentName?: string | null;
    /**
     * Indicates if this is the issuer's final year filing.
     * @type {boolean}
     * @memberof IssuerBase
     */
    lastFiling: boolean | null;
}



/**
 * Check if a given object implements the IssuerBase interface.
 */
export function instanceOfIssuerBase(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "telephone" in value;
    isInstance = isInstance && "taxYear" in value;
    isInstance = isInstance && "countryCode" in value;
    isInstance = isInstance && "address" in value;
    isInstance = isInstance && "city" in value;
    isInstance = isInstance && "state" in value;
    isInstance = isInstance && "zip" in value;
    isInstance = isInstance && "lastFiling" in value;

    return isInstance;
}

export function IssuerBaseFromJSON(json: any): IssuerBase {
    return IssuerBaseFromJSONTyped(json, false);
}

export function IssuerBaseFromJSONTyped(json: any, ignoreDiscriminator: boolean): IssuerBase {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'dbaName': !exists(json, 'dbaName') ? undefined : json['dbaName'],
        'tin': !exists(json, 'tin') ? undefined : json['tin'],
        'referenceId': !exists(json, 'referenceId') ? undefined : json['referenceId'],
        'telephone': json['telephone'],
        'taxYear': json['taxYear'],
        'countryCode': json['countryCode'],
        'email': !exists(json, 'email') ? undefined : json['email'],
        'address': json['address'],
        'city': json['city'],
        'state': json['state'],
        'zip': json['zip'],
        'foreignProvince': !exists(json, 'foreignProvince') ? undefined : json['foreignProvince'],
        'transferAgentName': !exists(json, 'transferAgentName') ? undefined : json['transferAgentName'],
        'lastFiling': json['lastFiling'],
    };
}

export function IssuerBaseToJSON(value?: IssuerBase | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'dbaName': value.dbaName,
        'tin': value.tin,
        'referenceId': value.referenceId,
        'telephone': value.telephone,
        'taxYear': value.taxYear,
        'countryCode': value.countryCode,
        'email': value.email,
        'address': value.address,
        'city': value.city,
        'state': value.state,
        'zip': value.zip,
        'foreignProvince': value.foreignProvince,
        'transferAgentName': value.transferAgentName,
        'lastFiling': value.lastFiling,
    };
}
