/* tslint:disable */
/* eslint-disable */
/**
 * Avalara 1099 & W-9 API Definition
 * ## 🔐 Authentication  Use **username/password** or generate a **license key** from: *Avalara Portal → Settings → License and API Keys*.  [More on authentication methods](https://developer.avalara.com/avatax-dm-combined-erp/common-setup/authentication/authentication-methods/)  [Test your credentials](https://developer.avalara.com/avatax/test-credentials/)  ## 📘 API & SDK Documentation  [Avalara SDK (.NET) on GitHub](https://github.com/avadev/Avalara-SDK-DotNet#avalarasdk--the-unified-c-library-for-next-gen-avalara-services)  [Code Examples – 1099 API](https://github.com/avadev/Avalara-SDK-DotNet/blob/main/docs/A1099/V2/Class1099IssuersApi.md#call1099issuersget)
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@avalara.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../../../runtime';
/**
 * 
 * @export
 * @interface StateAndLocalWithholdingResponse
 */
export interface StateAndLocalWithholdingResponse {
    /**
     * 
     * @type {number}
     * @memberof StateAndLocalWithholdingResponse
     */
    stateTaxWithheld?: number;
    /**
     * 
     * @type {string}
     * @memberof StateAndLocalWithholdingResponse
     */
    state?: string;
    /**
     * 
     * @type {string}
     * @memberof StateAndLocalWithholdingResponse
     */
    stateIdNumber?: string;
    /**
     * 
     * @type {number}
     * @memberof StateAndLocalWithholdingResponse
     */
    stateIncome?: number;
    /**
     * 
     * @type {number}
     * @memberof StateAndLocalWithholdingResponse
     */
    localTaxWithheld?: number;
    /**
     * 
     * @type {string}
     * @memberof StateAndLocalWithholdingResponse
     */
    locality?: string;
    /**
     * 
     * @type {string}
     * @memberof StateAndLocalWithholdingResponse
     */
    localityIdNumber?: string | null;
    /**
     * 
     * @type {number}
     * @memberof StateAndLocalWithholdingResponse
     */
    localIncome?: number;
}



/**
 * Check if a given object implements the StateAndLocalWithholdingResponse interface.
 */
export function instanceOfStateAndLocalWithholdingResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function StateAndLocalWithholdingResponseFromJSON(json: any): StateAndLocalWithholdingResponse {
    return StateAndLocalWithholdingResponseFromJSONTyped(json, false);
}

export function StateAndLocalWithholdingResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): StateAndLocalWithholdingResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'stateTaxWithheld': !exists(json, 'stateTaxWithheld') ? undefined : json['stateTaxWithheld'],
        'state': !exists(json, 'state') ? undefined : json['state'],
        'stateIdNumber': !exists(json, 'stateIdNumber') ? undefined : json['stateIdNumber'],
        'stateIncome': !exists(json, 'stateIncome') ? undefined : json['stateIncome'],
        'localTaxWithheld': !exists(json, 'localTaxWithheld') ? undefined : json['localTaxWithheld'],
        'locality': !exists(json, 'locality') ? undefined : json['locality'],
        'localityIdNumber': !exists(json, 'localityIdNumber') ? undefined : json['localityIdNumber'],
        'localIncome': !exists(json, 'localIncome') ? undefined : json['localIncome'],
    };
}

export function StateAndLocalWithholdingResponseToJSON(value?: StateAndLocalWithholdingResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'stateTaxWithheld': value.stateTaxWithheld,
        'state': value.state,
        'stateIdNumber': value.stateIdNumber,
        'stateIncome': value.stateIncome,
        'localTaxWithheld': value.localTaxWithheld,
        'locality': value.locality,
        'localityIdNumber': value.localityIdNumber,
        'localIncome': value.localIncome,
    };
}
