/* tslint:disable */
/* eslint-disable */
/**
 * Avalara 1099 & W-9 API Definition
 * ## 🔐 Authentication  Generate a **license key** from: *[Avalara Portal](https://www.avalara.com/us/en/signin.html) → Settings → License and API Keys*.  [More on authentication methods](https://developer.avalara.com/avatax-dm-combined-erp/common-setup/authentication/authentication-methods/)  [Test your credentials](https://developer.avalara.com/avatax/test-credentials/)  ## 📘 API & SDK Documentation  [Avalara SDK (.NET) on GitHub](https://github.com/avadev/Avalara-SDK-DotNet#avalarasdk--the-unified-c-library-for-next-gen-avalara-services)  [Code Examples – 1099 API](https://github.com/avadev/Avalara-SDK-DotNet/blob/main/docs/A1099/V2/Class1099IssuersApi.md#call1099issuersget)
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@avalara.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Form1042SResponse } from './Form1042SResponse';
import {
    instanceOfForm1042SResponse,
    Form1042SResponseFromJSON,
    Form1042SResponseFromJSONTyped,
    Form1042SResponseToJSON,
} from './Form1042SResponse';
import type { Form1099DivResponse } from './Form1099DivResponse';
import {
    instanceOfForm1099DivResponse,
    Form1099DivResponseFromJSON,
    Form1099DivResponseFromJSONTyped,
    Form1099DivResponseToJSON,
} from './Form1099DivResponse';
import type { Form1099KResponse } from './Form1099KResponse';
import {
    instanceOfForm1099KResponse,
    Form1099KResponseFromJSON,
    Form1099KResponseFromJSONTyped,
    Form1099KResponseToJSON,
} from './Form1099KResponse';
import type { Form1099MiscResponse } from './Form1099MiscResponse';
import {
    instanceOfForm1099MiscResponse,
    Form1099MiscResponseFromJSON,
    Form1099MiscResponseFromJSONTyped,
    Form1099MiscResponseToJSON,
} from './Form1099MiscResponse';
import type { Form1099NecResponse } from './Form1099NecResponse';
import {
    instanceOfForm1099NecResponse,
    Form1099NecResponseFromJSON,
    Form1099NecResponseFromJSONTyped,
    Form1099NecResponseToJSON,
} from './Form1099NecResponse';
import type { FormResponseBase } from './FormResponseBase';
import {
    instanceOfFormResponseBase,
    FormResponseBaseFromJSON,
    FormResponseBaseFromJSONTyped,
    FormResponseBaseToJSON,
} from './FormResponseBase';

/**
 * @type Update1099Form200Response
 * 
 * @export
 */
export type Update1099Form200Response = Form1042SResponse | Form1099DivResponse | Form1099KResponse | Form1099MiscResponse | Form1099NecResponse | FormResponseBase;

export function Update1099Form200ResponseFromJSON(json: any): Update1099Form200Response {
    return Update1099Form200ResponseFromJSONTyped(json, false);
}

export function Update1099Form200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): Update1099Form200Response {
    if (json == null) {
        return json;
    }
    if (instanceOfForm1042SResponse(json)) {
        return Form1042SResponseFromJSONTyped(json, true);
    }
    if (instanceOfForm1099DivResponse(json)) {
        return Form1099DivResponseFromJSONTyped(json, true);
    }
    if (instanceOfForm1099KResponse(json)) {
        return Form1099KResponseFromJSONTyped(json, true);
    }
    if (instanceOfForm1099MiscResponse(json)) {
        return Form1099MiscResponseFromJSONTyped(json, true);
    }
    if (instanceOfForm1099NecResponse(json)) {
        return Form1099NecResponseFromJSONTyped(json, true);
    }
    if (instanceOfFormResponseBase(json)) {
        return FormResponseBaseFromJSONTyped(json, true);
    }
}

export function Update1099Form200ResponseToJSON(value?: Update1099Form200Response | null): any {
    if (value == null) {
        return value;
    }

    if (instanceOfForm1042SResponse(value)) {
        return Form1042SResponseToJSON(value as Form1042SResponse);
    }
    if (instanceOfForm1099DivResponse(value)) {
        return Form1099DivResponseToJSON(value as Form1099DivResponse);
    }
    if (instanceOfForm1099KResponse(value)) {
        return Form1099KResponseToJSON(value as Form1099KResponse);
    }
    if (instanceOfForm1099MiscResponse(value)) {
        return Form1099MiscResponseToJSON(value as Form1099MiscResponse);
    }
    if (instanceOfForm1099NecResponse(value)) {
        return Form1099NecResponseToJSON(value as Form1099NecResponse);
    }
    if (instanceOfFormResponseBase(value)) {
        return FormResponseBaseToJSON(value as FormResponseBase);
    }

    return {};
}

