/* tslint:disable */
/* eslint-disable */
/**
 * Avalara 1099 & W-9 API Definition
 * ## 🔐 Authentication  Generate a **license key** from: *[Avalara Portal](https://www.avalara.com/us/en/signin.html) → Settings → License and API Keys*.  [More on authentication methods](https://developer.avalara.com/avatax-dm-combined-erp/common-setup/authentication/authentication-methods/)  [Test your credentials](https://developer.avalara.com/avatax/test-credentials/)  ## 📘 API & SDK Documentation  [Avalara SDK (.NET) on GitHub](https://github.com/avadev/Avalara-SDK-DotNet#avalarasdk--the-unified-c-library-for-next-gen-avalara-services)  [Code Examples – 1099 API](https://github.com/avadev/Avalara-SDK-DotNet/blob/main/docs/A1099/V2/Class1099IssuersApi.md#call1099issuersget)
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@avalara.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../../../runtime';
import {
    EntryStatusResponse,
    EntryStatusResponseFromJSON,
    EntryStatusResponseFromJSONTyped,
    EntryStatusResponseToJSON,
} from './EntryStatusResponse';

/**
 * 
 * @export
 * @interface W8BenFormResponse
 */
export interface W8BenFormResponse {
    /**
     * The form type (always "W8Ben" for this model).
     * @type {string}
     * @memberof W8BenFormResponse
     */
    readonly type?: W8BenFormResponseTypeEnum;
    /**
     * The name of the individual or entity associated with the form.
     * @type {string}
     * @memberof W8BenFormResponse
     */
    name?: string;
    /**
     * The country of citizenship.
     * @type {string}
     * @memberof W8BenFormResponse
     */
    citizenshipCountry?: string;
    /**
     * The residential address of the individual or entity.
     * @type {string}
     * @memberof W8BenFormResponse
     */
    residenceAddress?: string;
    /**
     * The city of residence.
     * @type {string}
     * @memberof W8BenFormResponse
     */
    residenceCity?: string;
    /**
     * The state of residence.
     * @type {string}
     * @memberof W8BenFormResponse
     */
    residenceState?: string | null;
    /**
     * The ZIP code of the residence.
     * @type {string}
     * @memberof W8BenFormResponse
     */
    residenceZip?: string;
    /**
     * The country of residence.
     * @type {string}
     * @memberof W8BenFormResponse
     */
    residenceCountry?: string;
    /**
     * Indicates whether the residence address is the mailing address.
     * @type {boolean}
     * @memberof W8BenFormResponse
     */
    residenceIsMailing?: boolean;
    /**
     * The mailing address.
     * @type {string}
     * @memberof W8BenFormResponse
     */
    mailingAddress?: string | null;
    /**
     * The city of the mailing address.
     * @type {string}
     * @memberof W8BenFormResponse
     */
    mailingCity?: string | null;
    /**
     * The state of the mailing address.
     * @type {string}
     * @memberof W8BenFormResponse
     */
    mailingState?: string | null;
    /**
     * The ZIP code of the mailing address.
     * @type {string}
     * @memberof W8BenFormResponse
     */
    mailingZip?: string | null;
    /**
     * The country of the mailing address.
     * @type {string}
     * @memberof W8BenFormResponse
     */
    mailingCountry?: string | null;
    /**
     * Tax Identification Number (TIN) type.
     * @type {string}
     * @memberof W8BenFormResponse
     */
    tinType?: string | null;
    /**
     * The taxpayer identification number (TIN).
     * @type {string}
     * @memberof W8BenFormResponse
     */
    tin?: string | null;
    /**
     * Indicates whether a foreign TIN is not required.
     * @type {boolean}
     * @memberof W8BenFormResponse
     */
    foreignTinNotRequired?: boolean;
    /**
     * The foreign taxpayer identification number (TIN).
     * @type {string}
     * @memberof W8BenFormResponse
     */
    foreignTin?: string | null;
    /**
     * A reference number for the form.
     * @type {string}
     * @memberof W8BenFormResponse
     */
    referenceNumber?: string | null;
    /**
     * The birthday of the individual associated with the form.
     * @type {Date}
     * @memberof W8BenFormResponse
     */
    birthday?: Date | null;
    /**
     * The country for which the treaty applies.
     * @type {string}
     * @memberof W8BenFormResponse
     */
    treatyCountry?: string;
    /**
     * The specific article of the treaty being claimed.
     * @type {string}
     * @memberof W8BenFormResponse
     */
    treatyArticle?: string | null;
    /**
     * The reasons for claiming treaty benefits.
     * @type {string}
     * @memberof W8BenFormResponse
     */
    treatyReasons?: string | null;
    /**
     * The withholding rate applied as per the treaty.
     * @type {string}
     * @memberof W8BenFormResponse
     */
    withholdingRate?: string | null;
    /**
     * The type of income covered by the treaty.
     * @type {string}
     * @memberof W8BenFormResponse
     */
    incomeType?: string | null;
    /**
     * The name of the signer of the form.
     * @type {string}
     * @memberof W8BenFormResponse
     */
    signerName?: string | null;
    /**
     * The capacity in which the signer is signing the form.
     * @type {string}
     * @memberof W8BenFormResponse
     */
    signerCapacity?: string | null;
    /**
     * The unique identifier for the form.
     * @type {string}
     * @memberof W8BenFormResponse
     */
    id?: string;
    /**
     * The entry status information for the form.
     * @type {EntryStatusResponse}
     * @memberof W8BenFormResponse
     */
    entryStatus?: EntryStatusResponse;
    /**
     * A reference identifier for the form.
     * @type {string}
     * @memberof W8BenFormResponse
     */
    referenceId?: string | null;
    /**
     * The ID of the associated company.
     * @type {string}
     * @memberof W8BenFormResponse
     */
    companyId?: string;
    /**
     * The display name associated with the form.
     * @type {string}
     * @memberof W8BenFormResponse
     */
    displayName?: string;
    /**
     * The email address of the individual associated with the form.
     * @type {string}
     * @memberof W8BenFormResponse
     */
    email?: string | null;
    /**
     * Indicates whether the form is archived.
     * @type {boolean}
     * @memberof W8BenFormResponse
     */
    archived?: boolean;
    /**
     * Form ID of previous version.
     * @type {string}
     * @memberof W8BenFormResponse
     */
    ancestorId?: string | null;
    /**
     * The signature of the form.
     * @type {string}
     * @memberof W8BenFormResponse
     */
    signature?: string | null;
    /**
     * The date the form was signed.
     * @type {Date}
     * @memberof W8BenFormResponse
     */
    signedDate?: Date | null;
    /**
     * The date when e-delivery was consented.
     * @type {Date}
     * @memberof W8BenFormResponse
     */
    eDeliveryConsentedAt?: Date | null;
    /**
     * The creation date of the form.
     * @type {Date}
     * @memberof W8BenFormResponse
     */
    createdAt?: Date;
    /**
     * The last updated date of the form.
     * @type {Date}
     * @memberof W8BenFormResponse
     */
    updatedAt?: Date;
}

/**
* @export
* @enum {string}
*/
export enum W8BenFormResponseTypeEnum {
    W4 = 'W4',
    W8Ben = 'W8Ben',
    W8BenE = 'W8BenE',
    W8Imy = 'W8Imy',
    W9 = 'W9'
}

/**
 * Check if a given object implements the W8BenFormResponse interface.
 */
export function instanceOfW8BenFormResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function W8BenFormResponseFromJSON(json: any): W8BenFormResponse {
    return W8BenFormResponseFromJSONTyped(json, false);
}

export function W8BenFormResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): W8BenFormResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': !exists(json, 'type') ? undefined : json['type'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'citizenshipCountry': !exists(json, 'citizenshipCountry') ? undefined : json['citizenshipCountry'],
        'residenceAddress': !exists(json, 'residenceAddress') ? undefined : json['residenceAddress'],
        'residenceCity': !exists(json, 'residenceCity') ? undefined : json['residenceCity'],
        'residenceState': !exists(json, 'residenceState') ? undefined : json['residenceState'],
        'residenceZip': !exists(json, 'residenceZip') ? undefined : json['residenceZip'],
        'residenceCountry': !exists(json, 'residenceCountry') ? undefined : json['residenceCountry'],
        'residenceIsMailing': !exists(json, 'residenceIsMailing') ? undefined : json['residenceIsMailing'],
        'mailingAddress': !exists(json, 'mailingAddress') ? undefined : json['mailingAddress'],
        'mailingCity': !exists(json, 'mailingCity') ? undefined : json['mailingCity'],
        'mailingState': !exists(json, 'mailingState') ? undefined : json['mailingState'],
        'mailingZip': !exists(json, 'mailingZip') ? undefined : json['mailingZip'],
        'mailingCountry': !exists(json, 'mailingCountry') ? undefined : json['mailingCountry'],
        'tinType': !exists(json, 'tinType') ? undefined : json['tinType'],
        'tin': !exists(json, 'tin') ? undefined : json['tin'],
        'foreignTinNotRequired': !exists(json, 'foreignTinNotRequired') ? undefined : json['foreignTinNotRequired'],
        'foreignTin': !exists(json, 'foreignTin') ? undefined : json['foreignTin'],
        'referenceNumber': !exists(json, 'referenceNumber') ? undefined : json['referenceNumber'],
        'birthday': !exists(json, 'birthday') ? undefined : (json['birthday'] === null ? null : new Date(json['birthday'])),
        'treatyCountry': !exists(json, 'treatyCountry') ? undefined : json['treatyCountry'],
        'treatyArticle': !exists(json, 'treatyArticle') ? undefined : json['treatyArticle'],
        'treatyReasons': !exists(json, 'treatyReasons') ? undefined : json['treatyReasons'],
        'withholdingRate': !exists(json, 'withholdingRate') ? undefined : json['withholdingRate'],
        'incomeType': !exists(json, 'incomeType') ? undefined : json['incomeType'],
        'signerName': !exists(json, 'signerName') ? undefined : json['signerName'],
        'signerCapacity': !exists(json, 'signerCapacity') ? undefined : json['signerCapacity'],
        'id': !exists(json, 'id') ? undefined : json['id'],
        'entryStatus': !exists(json, 'entryStatus') ? undefined : EntryStatusResponseFromJSON(json['entryStatus']),
        'referenceId': !exists(json, 'referenceId') ? undefined : json['referenceId'],
        'companyId': !exists(json, 'companyId') ? undefined : json['companyId'],
        'displayName': !exists(json, 'displayName') ? undefined : json['displayName'],
        'email': !exists(json, 'email') ? undefined : json['email'],
        'archived': !exists(json, 'archived') ? undefined : json['archived'],
        'ancestorId': !exists(json, 'ancestorId') ? undefined : json['ancestorId'],
        'signature': !exists(json, 'signature') ? undefined : json['signature'],
        'signedDate': !exists(json, 'signedDate') ? undefined : (json['signedDate'] === null ? null : new Date(json['signedDate'])),
        'eDeliveryConsentedAt': !exists(json, 'eDeliveryConsentedAt') ? undefined : (json['eDeliveryConsentedAt'] === null ? null : new Date(json['eDeliveryConsentedAt'])),
        'createdAt': !exists(json, 'createdAt') ? undefined : (new Date(json['createdAt'])),
        'updatedAt': !exists(json, 'updatedAt') ? undefined : (new Date(json['updatedAt'])),
    };
}

export function W8BenFormResponseToJSON(value?: W8BenFormResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'citizenshipCountry': value.citizenshipCountry,
        'residenceAddress': value.residenceAddress,
        'residenceCity': value.residenceCity,
        'residenceState': value.residenceState,
        'residenceZip': value.residenceZip,
        'residenceCountry': value.residenceCountry,
        'residenceIsMailing': value.residenceIsMailing,
        'mailingAddress': value.mailingAddress,
        'mailingCity': value.mailingCity,
        'mailingState': value.mailingState,
        'mailingZip': value.mailingZip,
        'mailingCountry': value.mailingCountry,
        'tinType': value.tinType,
        'tin': value.tin,
        'foreignTinNotRequired': value.foreignTinNotRequired,
        'foreignTin': value.foreignTin,
        'referenceNumber': value.referenceNumber,
        'birthday': value.birthday === undefined ? undefined : (value.birthday === null ? null : value.birthday.toISOString().substr(0,10)),
        'treatyCountry': value.treatyCountry,
        'treatyArticle': value.treatyArticle,
        'treatyReasons': value.treatyReasons,
        'withholdingRate': value.withholdingRate,
        'incomeType': value.incomeType,
        'signerName': value.signerName,
        'signerCapacity': value.signerCapacity,
        'id': value.id,
        'entryStatus': EntryStatusResponseToJSON(value.entryStatus),
        'referenceId': value.referenceId,
        'companyId': value.companyId,
        'displayName': value.displayName,
        'email': value.email,
        'archived': value.archived,
        'ancestorId': value.ancestorId,
        'signature': value.signature,
        'signedDate': value.signedDate === undefined ? undefined : (value.signedDate === null ? null : value.signedDate.toISOString()),
        'eDeliveryConsentedAt': value.eDeliveryConsentedAt === undefined ? undefined : (value.eDeliveryConsentedAt === null ? null : value.eDeliveryConsentedAt.toISOString()),
        'createdAt': value.createdAt === undefined ? undefined : (value.createdAt.toISOString()),
        'updatedAt': value.updatedAt === undefined ? undefined : (value.updatedAt.toISOString()),
    };
}
