/* tslint:disable */
/* eslint-disable */
/**
 * Avalara 1099 & W-9 API Definition
 * ## 🔐 Authentication  Generate a **license key** from: *[Avalara Portal](https://www.avalara.com/us/en/signin.html) → Settings → License and API Keys*.  [More on authentication methods](https://developer.avalara.com/avatax-dm-combined-erp/common-setup/authentication/authentication-methods/)  [Test your credentials](https://developer.avalara.com/avatax/test-credentials/)  ## 📘 API & SDK Documentation  [Avalara SDK (.NET) on GitHub](https://github.com/avadev/Avalara-SDK-DotNet#avalarasdk--the-unified-c-library-for-next-gen-avalara-services)  [Code Examples – 1099 API](https://github.com/avadev/Avalara-SDK-DotNet/blob/main/docs/A1099/V2/Class1099IssuersApi.md#call1099issuersget)
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@avalara.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../../../runtime';
/**
 * 
 * @export
 * @interface W9FormMinimalRequest
 */
export interface W9FormMinimalRequest {
    /**
     * The form type (always "w9" for this model).
     * @type {string}
     * @memberof W9FormMinimalRequest
     */
    readonly type?: W9FormMinimalRequestTypeEnum;
    /**
     * The email address of the individual associated with the form.
     * @type {string}
     * @memberof W9FormMinimalRequest
     */
    email: string;
    /**
     * The name of the individual or entity associated with the form.
     * @type {string}
     * @memberof W9FormMinimalRequest
     */
    name: string;
    /**
     * The account number associated with the form.
     * @type {string}
     * @memberof W9FormMinimalRequest
     */
    accountNumber?: string | null;
    /**
     * The ID of the associated company. Required when creating a form.
     * @type {string}
     * @memberof W9FormMinimalRequest
     */
    companyId?: string;
    /**
     * A reference identifier for the form.
     * @type {string}
     * @memberof W9FormMinimalRequest
     */
    referenceId?: string | null;
}

/**
* @export
* @enum {string}
*/
export enum W9FormMinimalRequestTypeEnum {
    W4 = 'W4',
    W8Ben = 'W8Ben',
    W8BenE = 'W8BenE',
    W8Imy = 'W8Imy',
    W9 = 'W9'
}

/**
 * Check if a given object implements the W9FormMinimalRequest interface.
 */
export function instanceOfW9FormMinimalRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "email" in value;
    isInstance = isInstance && "name" in value;

    return isInstance;
}

export function W9FormMinimalRequestFromJSON(json: any): W9FormMinimalRequest {
    return W9FormMinimalRequestFromJSONTyped(json, false);
}

export function W9FormMinimalRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): W9FormMinimalRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': !exists(json, 'type') ? undefined : json['type'],
        'email': json['email'],
        'name': json['name'],
        'accountNumber': !exists(json, 'accountNumber') ? undefined : json['accountNumber'],
        'companyId': !exists(json, 'companyId') ? undefined : json['companyId'],
        'referenceId': !exists(json, 'referenceId') ? undefined : json['referenceId'],
    };
}

export function W9FormMinimalRequestToJSON(value?: W9FormMinimalRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'email': value.email,
        'name': value.name,
        'accountNumber': value.accountNumber,
        'companyId': value.companyId,
        'referenceId': value.referenceId,
    };
}
