/* tslint:disable */
/* eslint-disable */
/**
 * Avalara E-Invoicing API
 * An API that supports sending data for an E-Invoicing compliance use-case.
 *
 * The version of the OpenAPI document: 1.6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../../../runtime';
import {
    Extension,
    ExtensionFromJSON,
    ExtensionFromJSONTyped,
    ExtensionToJSON,
} from './Extension';

/**
 * 
 * @export
 * @interface Identifier
 */
export interface Identifier {
    /**
     * Identifier name (e.g., Peppol Participant ID).
     * @type {string}
     * @memberof Identifier
     */
    name: string;
    /**
     * Display name of the identifier.
     * @type {string}
     * @memberof Identifier
     */
    displayName?: string;
    /**
     * Value of the identifier.
     * @type {string}
     * @memberof Identifier
     */
    value: string;
    /**
     * Optional array used to carry additional metadata or configuration values for the identifier.
     * @type {Array<Extension>}
     * @memberof Identifier
     */
    extensions?: Array<Extension>;
}



/**
 * Check if a given object implements the Identifier interface.
 */
export function instanceOfIdentifier(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "value" in value;

    return isInstance;
}

export function IdentifierFromJSON(json: any): Identifier {
    return IdentifierFromJSONTyped(json, false);
}

export function IdentifierFromJSONTyped(json: any, ignoreDiscriminator: boolean): Identifier {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'displayName': !exists(json, 'displayName') ? undefined : json['displayName'],
        'value': json['value'],
        'extensions': !exists(json, 'extensions') ? undefined : ((json['extensions'] as Array<any>)?.map(ExtensionFromJSON)),
    };
}

export function IdentifierToJSON(value?: Identifier | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'displayName': value.displayName,
        'value': value.value,
        'extensions': value.extensions === undefined ? undefined : ((value.extensions as Array<any>)?.map(ExtensionToJSON)),
    };
}
