/* tslint:disable */
/* eslint-disable */
/**
 * Avalara E-Invoicing API
 * An API that supports sending data for an E-Invoicing compliance use-case.
 *
 * The version of the OpenAPI document: 1.6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../../../runtime';
/**
 * Represents a single report with full details including metadata and associated transaction IDs.
 * @export
 * @interface ReportItem
 */
export interface ReportItem {
    /**
     * The unique ID for this report.
     * @type {string}
     * @memberof ReportItem
     */
    reportId?: string;
    /**
     * The unique ID of the job that generated this report.
     * @type {string}
     * @memberof ReportItem
     */
    jobId?: string | null;
    /**
     * The date and time when the report was generated.
     * @type {Date}
     * @memberof ReportItem
     */
    reportGenerateDate?: Date;
    /**
     * The start date of the reporting period.
     * @type {Date}
     * @memberof ReportItem
     */
    reportFrom?: Date | null;
    /**
     * The end date of the reporting period.
     * @type {Date}
     * @memberof ReportItem
     */
    reportTo?: Date | null;
    /**
     * The two-letter ISO-3166 country code for which this report was generated.
     * @type {string}
     * @memberof ReportItem
     */
    countryCode?: string;
    /**
     * The e-invoicing mandate for the specified country.
     * @type {string}
     * @memberof ReportItem
     */
    countryMandate?: string;
    /**
     * The type of document covered by this report.
     * @type {string}
     * @memberof ReportItem
     */
    documentType?: string | null;
    /**
     * The sub-type of the document.
     * @type {string}
     * @memberof ReportItem
     */
    documentSubType?: string | null;
    /**
     * An internal reference path for the report.
     * @type {string}
     * @memberof ReportItem
     */
    reportReference?: string | null;
    /**
     * The name of the report file.
     * @type {string}
     * @memberof ReportItem
     */
    reportName?: string;
    /**
     * The current status of the report. Possible values include: PENDING, PROCESSING, COMPLETED, FAILED, SENT_TO_PPF, ERROR.
     * @type {string}
     * @memberof ReportItem
     */
    status?: string;
    /**
     * The MIME type of the report file.
     * @type {string}
     * @memberof ReportItem
     */
    reportFormatMimetypes?: string;
    /**
     * The tenant identifier associated with this report.
     * @type {string}
     * @memberof ReportItem
     */
    tenantId?: string;
    /**
     * The name of the tax authority for this report.
     * @type {string}
     * @memberof ReportItem
     */
    taName?: string;
    /**
     * The total invoice amount covered by this report.
     * @type {number}
     * @memberof ReportItem
     */
    taxInvoiceAmount?: number | null;
    /**
     * The total tax amount covered by this report.
     * @type {number}
     * @memberof ReportItem
     */
    totalTaxAmount?: number | null;
    /**
     * Additional report metadata (free-form JSON). Contents vary by country mandate.
     * @type {object}
     * @memberof ReportItem
     */
    metadata?: object;
    /**
     * List of transaction IDs associated with this report.
     * @type {Array<string>}
     * @memberof ReportItem
     */
    transactionIds?: Array<string>;
}



/**
 * Check if a given object implements the ReportItem interface.
 */
export function instanceOfReportItem(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ReportItemFromJSON(json: any): ReportItem {
    return ReportItemFromJSONTyped(json, false);
}

export function ReportItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReportItem {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'reportId': !exists(json, 'reportId') ? undefined : json['reportId'],
        'jobId': !exists(json, 'jobId') ? undefined : json['jobId'],
        'reportGenerateDate': !exists(json, 'reportGenerateDate') ? undefined : (new Date(json['reportGenerateDate'])),
        'reportFrom': !exists(json, 'reportFrom') ? undefined : (json['reportFrom'] === null ? null : new Date(json['reportFrom'])),
        'reportTo': !exists(json, 'reportTo') ? undefined : (json['reportTo'] === null ? null : new Date(json['reportTo'])),
        'countryCode': !exists(json, 'countryCode') ? undefined : json['countryCode'],
        'countryMandate': !exists(json, 'countryMandate') ? undefined : json['countryMandate'],
        'documentType': !exists(json, 'documentType') ? undefined : json['documentType'],
        'documentSubType': !exists(json, 'documentSubType') ? undefined : json['documentSubType'],
        'reportReference': !exists(json, 'reportReference') ? undefined : json['reportReference'],
        'reportName': !exists(json, 'reportName') ? undefined : json['reportName'],
        'status': !exists(json, 'status') ? undefined : json['status'],
        'reportFormatMimetypes': !exists(json, 'reportFormatMimetypes') ? undefined : json['reportFormatMimetypes'],
        'tenantId': !exists(json, 'tenantId') ? undefined : json['tenantId'],
        'taName': !exists(json, 'taName') ? undefined : json['taName'],
        'taxInvoiceAmount': !exists(json, 'taxInvoiceAmount') ? undefined : json['taxInvoiceAmount'],
        'totalTaxAmount': !exists(json, 'totalTaxAmount') ? undefined : json['totalTaxAmount'],
        'metadata': !exists(json, 'metadata') ? undefined : json['metadata'],
        'transactionIds': !exists(json, 'transactionIds') ? undefined : json['transactionIds'],
    };
}

export function ReportItemToJSON(value?: ReportItem | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'reportId': value.reportId,
        'jobId': value.jobId,
        'reportGenerateDate': value.reportGenerateDate === undefined ? undefined : (value.reportGenerateDate.toISOString()),
        'reportFrom': value.reportFrom === undefined ? undefined : (value.reportFrom === null ? null : value.reportFrom.toISOString().substr(0,10)),
        'reportTo': value.reportTo === undefined ? undefined : (value.reportTo === null ? null : value.reportTo.toISOString().substr(0,10)),
        'countryCode': value.countryCode,
        'countryMandate': value.countryMandate,
        'documentType': value.documentType,
        'documentSubType': value.documentSubType,
        'reportReference': value.reportReference,
        'reportName': value.reportName,
        'status': value.status,
        'reportFormatMimetypes': value.reportFormatMimetypes,
        'tenantId': value.tenantId,
        'taName': value.taName,
        'taxInvoiceAmount': value.taxInvoiceAmount,
        'totalTaxAmount': value.totalTaxAmount,
        'metadata': value.metadata,
        'transactionIds': value.transactionIds,
    };
}
