/* tslint:disable */
/* eslint-disable */
/**
 * Avalara E-Invoicing API
 * An API that supports sending data for an E-Invoicing compliance use-case.
 *
 * The version of the OpenAPI document: 1.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../../../runtime';
import {
    TradingPartner,
    TradingPartnerFromJSON,
    TradingPartnerFromJSONTyped,
    TradingPartnerToJSON,
} from './TradingPartner';

/**
 * 
 * @export
 * @interface SearchParticipants200Response
 */
export interface SearchParticipants200Response {
    /**
     * The count of records in the result set.
     * @type {number}
     * @memberof SearchParticipants200Response
     */
    recordSetCount?: number;
    /**
     * The next page link to get the next set of results.
     * @type {string}
     * @memberof SearchParticipants200Response
     */
    nextLink?: string;
    /**
     * 
     * @type {Array<TradingPartner>}
     * @memberof SearchParticipants200Response
     */
    value?: Array<TradingPartner>;
}



/**
 * Check if a given object implements the SearchParticipants200Response interface.
 */
export function instanceOfSearchParticipants200Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function SearchParticipants200ResponseFromJSON(json: any): SearchParticipants200Response {
    return SearchParticipants200ResponseFromJSONTyped(json, false);
}

export function SearchParticipants200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchParticipants200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'recordSetCount': !exists(json, '@recordSetCount') ? undefined : json['@recordSetCount'],
        'nextLink': !exists(json, '@nextLink') ? undefined : json['@nextLink'],
        'value': !exists(json, 'value') ? undefined : ((json['value'] as Array<any>)?.map(TradingPartnerFromJSON)),
    };
}

export function SearchParticipants200ResponseToJSON(value?: SearchParticipants200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        '@recordSetCount': value.recordSetCount,
        '@nextLink': value.nextLink,
        'value': value.value === undefined ? undefined : ((value.value as Array<any>)?.map(TradingPartnerToJSON)),
    };
}
