/* tslint:disable */
/* eslint-disable */
/**
 * Avalara E-Invoicing API
 * An API that supports sending data for an E-Invoicing compliance use-case.
 *
 * The version of the OpenAPI document: 1.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../../../runtime';
/**
 * 
 * @export
 * @interface SignatureSignature
 */
export interface SignatureSignature {
    /**
     * 
     * @type {string}
     * @memberof SignatureSignature
     */
    type: SignatureSignatureTypeEnum;
    /**
     * HMAC key for authentication
     * @type {string}
     * @memberof SignatureSignature
     */
    key: string;
    /**
     * HMAC algorithm for authentication
     * @type {string}
     * @memberof SignatureSignature
     */
    algorithm: SignatureSignatureAlgorithmEnum;
}

/**
* @export
* @enum {string}
*/
export enum SignatureSignatureTypeEnum {
    None = 'none',
    Hmac = 'hmac'
}/**
* @export
* @enum {string}
*/
export enum SignatureSignatureAlgorithmEnum {
    Sha256 = 'sha256',
    Sha384 = 'sha384',
    Sha512 = 'sha512'
}

/**
 * Check if a given object implements the SignatureSignature interface.
 */
export function instanceOfSignatureSignature(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "type" in value;
    isInstance = isInstance && "key" in value;
    isInstance = isInstance && "algorithm" in value;

    return isInstance;
}

export function SignatureSignatureFromJSON(json: any): SignatureSignature {
    return SignatureSignatureFromJSONTyped(json, false);
}

export function SignatureSignatureFromJSONTyped(json: any, ignoreDiscriminator: boolean): SignatureSignature {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': json['type'],
        'key': json['key'],
        'algorithm': json['algorithm'],
    };
}

export function SignatureSignatureToJSON(value?: SignatureSignature | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': value.type,
        'key': value.key,
        'algorithm': value.algorithm,
    };
}
