/* tslint:disable */
/* eslint-disable */
/**
 * Avalara E-Invoicing API
 * An API that supports sending data for an E-Invoicing compliance use-case.
 *
 * The version of the OpenAPI document: 1.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../../../runtime';
import {
    EventSubscription,
    EventSubscriptionFromJSON,
    EventSubscriptionFromJSONTyped,
    EventSubscriptionToJSON,
} from './EventSubscription';
import {
    SignatureSignature,
    SignatureSignatureFromJSON,
    SignatureSignatureFromJSONTyped,
    SignatureSignatureToJSON,
} from './SignatureSignature';

/**
 * 
 * @export
 * @interface SubscriptionRegistration
 */
export interface SubscriptionRegistration {
    /**
     * Description of the subscription
     * @type {string}
     * @memberof SubscriptionRegistration
     */
    description?: string;
    /**
     * The URL of the webhook endpoint to which event messages will be delivered
     * @type {string}
     * @memberof SubscriptionRegistration
     */
    notificationUrl: string;
    /**
     * 
     * @type {SignatureSignature}
     * @memberof SubscriptionRegistration
     */
    signature: SignatureSignature;
    /**
     * 
     * @type {Array<EventSubscription>}
     * @memberof SubscriptionRegistration
     */
    events: Array<EventSubscription>;
}



/**
 * Check if a given object implements the SubscriptionRegistration interface.
 */
export function instanceOfSubscriptionRegistration(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "notificationUrl" in value;
    isInstance = isInstance && "signature" in value;
    isInstance = isInstance && "events" in value;

    return isInstance;
}

export function SubscriptionRegistrationFromJSON(json: any): SubscriptionRegistration {
    return SubscriptionRegistrationFromJSONTyped(json, false);
}

export function SubscriptionRegistrationFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubscriptionRegistration {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'description': !exists(json, 'description') ? undefined : json['description'],
        'notificationUrl': json['notificationUrl'],
        'signature': SignatureSignatureFromJSON(json['signature']),
        'events': ((json['events'] as Array<any>)?.map(EventSubscriptionFromJSON)),
    };
}

export function SubscriptionRegistrationToJSON(value?: SubscriptionRegistration | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'description': value.description,
        'notificationUrl': value.notificationUrl,
        'signature': SignatureSignatureToJSON(value.signature),
        'events': ((value.events as Array<any>)?.map(EventSubscriptionToJSON)),
    };
}
