/* tslint:disable */
/* eslint-disable */
/**
 * Avalara E-Invoicing API
 * An API that supports sending data for an E-Invoicing compliance use-case.
 *
 * The version of the OpenAPI document: 1.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../../../runtime';
/**
 * Workflow ID list
 * @export
 * @interface WorkflowIds
 */
export interface WorkflowIds {
    /**
     * The name of this workflow
     * @type {string}
     * @memberof WorkflowIds
     */
    name?: string;
    /**
     * Workflow description
     * @type {string}
     * @memberof WorkflowIds
     */
    description?: string;
}



/**
 * Check if a given object implements the WorkflowIds interface.
 */
export function instanceOfWorkflowIds(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function WorkflowIdsFromJSON(json: any): WorkflowIds {
    return WorkflowIdsFromJSONTyped(json, false);
}

export function WorkflowIdsFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkflowIds {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'description': !exists(json, 'description') ? undefined : json['description'],
    };
}

export function WorkflowIdsToJSON(value?: WorkflowIds | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'description': value.description,
    };
}
